"""Curated historical facts; never copies/distributes provider events or lineup JSON.
Generate the redacted application catalog from the server-owned question bank.
"""
import json, pathlib, hashlib, random
ROOT=pathlib.Path(__file__).resolve().parents[2]
CLUBS={5:'Milan',31:'Liverpool',985:'Manchester United',27:'Bayern Münih',631:'Chelsea',418:'Real Madrid',13:'Atlético Madrid',16:'Dortmund',131:'Barcelona',583:'Paris Saint-Germain',281:'Manchester City',610:'Ajax',148:'Tottenham',897:'Deportivo',46:'Inter',141:'Galatasaray',36:'Fenerbahçe',368:'Sevilla',23826:'RB Leipzig',114:'Beşiktaş',33:'Schalke',12:'Roma',294:'Benfica',720:'Porto',162:'Monaco',506:'Juventus'}
# date | home | away | round | title | mechanic | answer(s in chronology) | alternatives | prompt | clock | score | result context | hint | UEFA match ID
ROWS='''2005-05-25|5|31|Final|İstanbul'da bir gece|timeline|Steven Gerrard;Vladimír Šmicer;Xabi Alonso||Liverpool'un ikinci yarıdaki üç golünü sırala.|54′–60′|3–3|Liverpool altı dakikalık geri dönüşle uzatmaya ulaştı. Penaltılarda Milan 2–3 Liverpool; kupa Liverpool'un oldu.|İlk gol bir kafa vuruşuydu. Son gol, kaleciden dönen penaltının tamamlanmasıydı.|80813
1999-05-26|985|27|Final|Son düdüğe kadar|timeline|Mario Basler;Teddy Sheringham;Ole Gunnar Solskjær||Finaldeki üç golü ilk golden son gole sırala.|6′ / 90+1′ / 90+3′|2–1|Basler'in erken golüne Manchester United ek sürede Sheringham ve Solskjær ile yanıt verdi.|Erken gelen serbest vuruş golünü, iki korner organizasyonu izledi.|56379
2008-05-21|985|631|Final|Moskova yağmurunda|hero|Edwin van der Sar|Petr Čech;Rio Ferdinand;Nemanja Vidić|Anelka'nın son penaltısını kurtararak seriyi bitiren kaleci kimdi?|Penaltı serisi|1–1|Van der Sar son vuruşu kurtardı. Manchester United penaltı serisini 6–5 kazandı.|Kaleci seçmelisin; maçın açık oyun golcüsünü değil.|301604
2014-05-24|418|13|Final|Lizbon'daki eşik|goal|Sergio Ramos|Gareth Bale;Cristiano Ronaldo;Karim Benzema|90+3'te kafa vuruşuyla beraberliği getirip finali uzatmaya taşıyan kimdi?|90+3′|4–1|Ramos'un golü 90 dakikayı 1–1'e getirdi. Real Madrid uzatmada üç gol daha buldu.|Belirleyici kafa vuruşu bir korner organizasyonundan geldi.|2011883
2013-05-25|16|27|Final|Wembley ışıkları|goal|Arjen Robben|Franck Ribéry;Mario Mandžukić;Thomas Müller|89. dakikada Bayern'in galibiyet golünü kim attı?|89′|1–2|Mandžukić ve Gündoğan'ın gollerinden sonra Robben son sözü söyledi.|Dar alandaki paslaşmanın ardından ceza sahasına yapılan koşuyu düşün.|2009612
2017-03-08|131|583|Son 16 · rövanş|Camp Nou'da son fırsat|goal|Sergi Roberto|Lionel Messi;Luis Suárez;Neymar|Ek sürede son golü atarak Barcelona'yı çeyrek finale taşıyan kimdi?|90+5′|6–1|Sergi Roberto, Neymar'ın ortasını tamamladı. Barcelona iki maç toplamında 6–5 ile tur atladı.|Gol, son bir yüksek topun savunma arkasına ulaştırılmasıyla geldi.|2019621
2022-05-04|418|281|Yarı final · rövanş|Bernabéu'da durmayan saat|timeline|Riyad Mahrez;Rodrygo · ilk gol;Rodrygo · ikinci gol;Karim Benzema||Bu maçtaki dört gol olayını sırala. Rodrygo'nun iki golü ayrı karttır.|73′–95′|3–1|Mahrez 73, Rodrygo 90 ve 90+1, Benzema penaltıdan 95. dakikada gol attı. Real Madrid toplamda 6–5 kazandı.|Deplasman ekibinin golü önce geldi; penaltı ise uzatma devresindeydi.|2034663
2019-05-08|610|148|Yarı final · rövanş|Amsterdam'da kalan saniyeler|hero|Lucas Moura|Harry Kane;Heung-min Son;Christian Eriksen|İkinci yarıda hat-trick yaparak Tottenham'ı finale taşıyan kimdi?|55′ / 59′ / 90+6′|2–3|Lucas Moura üç gol attı. Toplam skor 3–3'tü; Tottenham o dönemki deplasman golü kuralıyla ilerledi.|Üç gol de aynı oyuncudan ve ikinci yarıda geldi.|2027159
2019-05-07|31|131|Yarı final · rövanş|Anfield'da bir işaret|goal|Divock Origi|Georginio Wijnaldum;Sadio Mané;Jordan Henderson|Hızlı kullanılan korneri gole çeviren kimdi?|79′|4–0|Alexander-Arnold'un çabuk kornerini Origi tamamladı. Liverpool toplamda 4–3 ile finale çıktı.|Korneri kullananı değil, ceza alanında vuruşu yapanı arıyoruz.|2027160
2004-04-07|897|5|Çeyrek final · rövanş|Riazor'da hesap günü|score|Deportivo 4–0 Milan|Deportivo 3–0 Milan;Deportivo 4–1 Milan;Deportivo 3–1 Milan|Rövanşın maç sonu skoru neydi?|Maç sonu|4–0|İlk maçı 4–1 kaybeden Deportivo, rövanşı 4–0 kazanıp toplamda 5–4 ile ilerledi.|Maç skorunu seç; iki karşılaşmanın toplamını değil.|1059564
2009-05-06|631|131|Yarı final · rövanş|Londra'da son hücum|goal|Andrés Iniesta|Xavi;Samuel Eto'o;Lionel Messi|Ek sürede Barcelona'ya beraberliği getiren golü kim attı?|90+3′|1–1|Iniesta'nın golüyle iki maç toplamı 1–1 oldu. Barcelona dönemin deplasman golü kuralıyla finale çıktı.|Ceza sahası dışından gelen vuruşu ve kalabalık savunmayı hatırla.|302812
2010-04-28|131|46|Yarı final · rövanş|Camp Nou'da savunma sınavı|score|Inter 3–2 Barcelona|Inter 3–1 Barcelona;Inter 2–1 Barcelona;Inter 4–2 Barcelona|İki maç toplamında Inter lehine sonuç neydi?|İki maç toplamı|1–0|Barcelona rövanşı 1–0 kazandı; ilk maçı 3–1 kazanan Inter toplamda 3–2 ile tur atladı.|Tek maç skorunu değil, iki ayağın toplamını hesapla.|2000487
1999-11-03|141|5|Grup aşaması|Ali Sami Yen'de Avrupa gecesi|timeline|Capone;Hakan Şükür;Ümit Davala||Galatasaray'ın bu maçtaki üç golcüsünü gol sırasına diz.|30′ / 86′ / 90′|3–2|Capone, Hakan Şükür ve penaltıdan Ümit Davala'nın golleri Galatasaray'a UEFA Kupası yolunu açtı.|Son gol penaltıdan geldi; ondan önce bir kafa vuruşu vardı.|57067
2008-02-20|36|368|Son 16 · ilk maç|Kadıköy'de son hamle|goal|Semih Şentürk|Mateja Kežman;Alex de Souza;Diego Lugano|87. dakikada Fenerbahçe'yi 3–2 öne geçiren kimdi?|87′|3–2|Oyuna sonradan giren Semih Şentürk ilk maçın galibiyet golünü attı.|Belirleyici oyuncu bu maça yedek kulübesinde başladı.|301894
2017-12-06|23826|114|Grup aşaması|Almanya'da son grup gecesi|goal|Talisca|Cenk Tosun;Álvaro Negredo;Ryan Babel|Beşiktaş'a son dakikada galibiyeti getiren kimdi?|90′|1–2|Talisca'nın golü Beşiktaş'ın grup aşamasını yenilgisiz tamamlamasını sağladı.|İlk golün penaltı vuruşunu değil, beraberlikten sonraki son hücumu düşün.|2021679
2013-03-12|33|141|Son 16 · rövanş|Gelsenkirchen'de son koşu|goal|Umut Bulut|Burak Yılmaz;Hamit Altıntop;Didier Drogba|Ek sürede Galatasaray'ın galibiyet golünü kim attı?|90+5′|2–3|Umut Bulut son golü attı. Galatasaray iki maç toplamında 4–3 ile çeyrek finale çıktı.|Sorulan gol ilk yarıdaki iki golden biri değil.|2009594
2018-04-10|12|131|Çeyrek final · rövanş|Roma'da tribünlerin sesi|goal|Kostas Manolas|Edin Džeko;Daniele De Rossi;Cengiz Ünder|Roma'nın üçüncü golünü atan kimdi?|82′|3–0|Manolas'ın kafa golü toplam skoru 4–4 yaptı. Roma dönemin deplasman golü kuralıyla yarı finale çıktı.|Asisti yapanla kafa vuruşunu yapan oyuncuyu ayır.|2021705
2013-04-24|16|418|Yarı final · ilk maç|Sarı duvarın önünde|hero|Robert Lewandowski|Marco Reus;Mario Götze;İlkay Gündoğan|Dortmund'un dört golünün tamamını kim attı?|8′ / 50′ / 55′ / 66′|4–1|Lewandowski dördüncü golünü penaltıdan attı; Dortmund rövanş öncesi üstünlük kurdu.|Dört golün biri penaltıydı; asistleri değil golcüyü arıyoruz.|2009610
2003-04-23|985|418|Çeyrek final · rövanş|Old Trafford'da alkış|hero|Ronaldo Nazário|Raúl;Luís Figo;Zinédine Zidane|Real Madrid adına hat-trick yapan futbolcu kimdi?|12′ / 50′ / 59′|4–3|Ronaldo Nazário üç gol attı. Manchester United geceyi kazansa da Real Madrid toplamda 6–5 ile ilerledi.|Kazanan takım ile tur atlayan takım farklıydı; deplasman ekibinin golcüsünü bul.|1044119
2016-11-23|114|294|Grup aşaması|Boğaz'da iki perde|score|Beşiktaş 0–3 Benfica|Beşiktaş 1–3 Benfica;Beşiktaş 0–2 Benfica;Beşiktaş 1–2 Benfica|Soyunma odasına gidilirken ilk yarı skoru neydi?|İlk yarı|3–3|İlk yarı 0–3 bitti. Beşiktaş ikinci yarıda Tosun, Quaresma ve Aboubakar ile beraberliği yakaladı.|Son düdüğü değil, devre arasındaki tabelayı soruyoruz.|2019357
1996-10-30|985|36|Grup aşaması|Manchester'da sessiz an|goal|Elvir Bolić|Jay-Jay Okocha;Aykut Kocaman;Tayfun Korkut|Fenerbahçe'nin maçtaki tek golünü kim attı?|78′|0–1|Bolić'in golüyle Fenerbahçe, Manchester United'ı Old Trafford'da mağlup etti.|Uzaktan çekilen ve savunmaya da çarpan şutu düşün.|53226
2012-05-19|27|631|Final|Münih'te son vuruş|hero|Didier Drogba|Frank Lampard;Juan Mata;Salomon Kalou|Hem beraberlik golünü hem de serinin son penaltısını atan kimdi?|88′ / penaltı serisi|1–1|Drogba 88'de eşitledi. Chelsea penaltı serisini 4–3 kazanırken son vuruşu da o yaptı.|Bir kafa golü ve penaltı serisindeki son vuruş aynı oyuncuya ait.|2007693
2020-08-14|131|27|Çeyrek final · tek maç|Lizbon'da tabela|score|Barcelona 2–8 Bayern Münih|Barcelona 2–6 Bayern Münih;Barcelona 3–8 Bayern Münih;Barcelona 1–7 Bayern Münih|Tek maç üzerinden oynanan çeyrek finalin skoru neydi?|Maç sonu|2–8|Bayern Münih 8–2 kazandı. Bu çeyrek final pandemi dönemindeki Lizbon tek maç formatında oynandı.|Tabelada Barcelona solda, Bayern sağda. Rövanş veya toplam skor yok.|2030146
2018-05-26|418|31|Final|Kiev'de başlangıç düdüğü|xi|Dani Carvajal|Nacho;Achraf Hakimi;Gareth Bale|Real Madrid'in başlangıç 11'indeki eksik sağ beki seç.|İlk 11|3–1|Carvajal ilk 11'de başladı; sakatlanınca yerini Nacho aldı. Real Madrid 3–1 kazandı.|Maçı bitiren kadroyu değil, ilk düdükte sahada olanı arıyoruz.|2021711
1972-05-31|610|46|Final|Rotterdam'ın eski ışıkları|xi|Johan Neeskens|Johnny Rep;Johan Boskamp;Arnold Mühren|Ajax'ın başlangıç 11'indeki eksik 7 numara kimdi?|İlk 11 · 7 numara|2–0|Ajax, Cruyff'un iki golüyle Avrupa Şampiyon Kulüpler Kupası'nı kazandı. Neeskens başlangıç 11'indeydi.|Bu karşılaşma modern Şampiyonlar Ligi adı kullanılmadan önce oynandı.|63097
2004-05-26|162|720|Final|Gelsenkirchen'de iki hayal|xi|Carlos Alberto|Benni McCarthy;Dmitri Alenichev;Edgaras Jankauskas|Porto'nun başlangıç 11'indeki eksik hücum oyuncusu kimdi?|İlk 11|0–3|Carlos Alberto ilk 11'deydi ve ilk golü attı. Porto üç golle kupaya ulaştı.|Sonradan oyuna girenleri değil, Derlei ile başlayan oyuncuyu seç.|1065206
2007-05-23|5|31|Final|Atina'da yeniden karşılaşma|hero|Filippo Inzaghi|Kaká;Clarence Seedorf;Alberto Gilardino|Milan'ın finaldeki iki golünü de kim attı?|45′ / 82′|2–1|Inzaghi'nin iki golü Milan'a kupayı getirdi; Liverpool'un geç golü sonucu değiştirmedi.|Aynı oyuncu ilk yarının sonunda ve ikinci yarıda gol buldu.|300099
2009-05-27|131|985|Final|Roma'da ilk on bir|xi|Yaya Touré|Seydou Keita;Rafael Márquez;Dani Alves|Barcelona'nın başlangıç 11'indeki eksik oyuncuyu seç.|İlk 11|2–0|Yaya Touré savunmada başladı. Eto'o ve Messi'nin golleri Barcelona'ya kupayı getirdi.|Sakatlık ve cezalar nedeniyle savunmada alışılmadık bir tercih vardı.|302813
2010-05-22|27|46|Final|Madrid'de kupa gecesi|hero|Diego Milito|Samuel Eto'o;Wesley Sneijder;Goran Pandev|Inter'in iki golünü de atan kimdi?|35′ / 70′|0–2|Milito iki gol attı. Inter bu zaferle sezonu lig, kupa ve Avrupa şampiyonluğuyla tamamladı.|İki farklı devrede yapılan bitirici vuruşlar aynı oyuncudan geldi.|2000488
2011-05-28|131|985|Final|Wembley'de tahta|xi|David Villa|Bojan Krkić;Ibrahim Afellay;Seydou Keita|Barcelona'nın başlangıç 11'indeki eksik hücum oyuncusunu seç.|İlk 11|3–1|Villa ilk 11'deydi ve Barcelona'nın üçüncü golünü attı.|Pedro ve Messi'nin yanındaki başlangıç tercihini bul.|2003352
2015-06-06|506|131|Final|Berlin'de ilk adım|xi|Ivan Rakitić|Xavi;Sergi Roberto;Rafinha|Barcelona'nın başlangıç 11'indeki eksik orta saha kimdi?|İlk 11|1–3|Rakitić ilk 11'de başladı ve ilk golü attı. Xavi sonradan oyuna girdi.|Sezonun genel kadrosu değil, bu finalin başlangıç kadrosu belirleyici.|2015227
2016-05-28|418|13|Final|Milano'da son nokta|hero|Cristiano Ronaldo|Sergio Ramos;Gareth Bale;Luka Modrić|Penaltı serisinin son vuruşunu gole çeviren kimdi?|Penaltı serisi|1–1|Real Madrid penaltıları 5–3 kazandı; seriyi Cristiano Ronaldo'nun vuruşu bitirdi.|Normal süredeki golcü ile son penaltıyı atan oyuncuyu karıştırma.|2015789
2017-06-03|506|418|Final|Cardiff'te final ışığı|hero|Cristiano Ronaldo|Karim Benzema;Casemiro;Marco Asensio|Real Madrid adına iki gol atan oyuncu kimdi?|20′ / 64′|1–4|Cristiano Ronaldo iki gol attı. Real Madrid üst üste ikinci kez kupayı kazandı.|İlk ve üçüncü Real Madrid gollerinin sahibi aynıydı.|2019641
2019-06-01|148|31|Final|Madrid'de kadro kararı|xi|Harry Kane|Lucas Moura;Fernando Llorente;Erik Lamela|Tottenham'ın başlangıç 11'indeki eksik santrforu seç.|İlk 11|0–2|Kane başlangıç kadrosundaydı; Lucas Moura yedek başladı. Liverpool Salah ve Origi ile kazandı.|Yarı finalin kadrosunu değil, finalin ilk 11'ini düşün.|2025486'''
# Independently curated starting XI, grouped for a readable schematic pitch (not event coordinates).
XI={24:('Real Madrid',[["Navas"],["Marcelo","Ramos","Varane","?"],["Kroos","Casemiro","Modrić"],["Isco"],["Cristiano Ronaldo","Benzema"]]),25:('Ajax',[["Stuy"],["Krol","Blankenburg","Hulshoff","Suurbier"],["Mühren","Haan","?"],["Keizer","Cruyff","Swart"]]),26:('Porto',[["Vítor Baía"],["Nuno Valente","Ricardo Carvalho","Jorge Costa","Paulo Ferreira"],["Maniche","Costinha","Pedro Mendes"],["Deco"],["Derlei","?"]]),28:('Barcelona',[["Valdés"],["Sylvinho","Piqué","?","Puyol"],["Iniesta","Busquets","Xavi"],["Henry","Eto'o","Messi"]]),30:('Barcelona',[["Valdés"],["Abidal","Mascherano","Piqué","Dani Alves"],["Iniesta","Busquets","Xavi"],["Pedro","Messi","?"]]),31:('Barcelona',[["Ter Stegen"],["Jordi Alba","Mascherano","Piqué","Dani Alves"],["Iniesta","Busquets","?"],["Neymar","Suárez","Messi"]]),34:('Tottenham',[["Lloris"],["Rose","Vertonghen","Alderweireld","Trippier"],["Winks","Sissoko"],["Son","Dele Alli","Eriksen"],["?"]])}
SB={1:2302764,4:18241,5:18240,22:18237,24:18245,25:3750235,26:3752619,27:3750200,28:3750201,29:18235,30:18236,31:18242,32:18243,33:18244,34:22912}
SOURCE_OVERRIDES={
10:('UEFA · maç raporu','https://www.uefa.com/uefachampionsleague/news/019c-0e6c12450ff2-294c584e2602-1000--dazzling-depor-ditch-milan/'),
12:('UEFA · eşleşme raporu','https://www.uefa.com/uefachampionsleague/news/01e4-0e746f438ade-69d47b996827-1000--alves-reflects-on-big-loss/'),
13:('Galatasaray · kulüp arşivi','https://www.galatasaray.org/haber/futbol/o-gun-en-uzak-11-metre/33804'),
18:('UEFA · maç raporu','https://www.uefa.com/uefachampionsleague/news/0208-0e9f60a306c2-d00309689516-1000/'),
19:('UEFA · maç raporu','https://www.uefa.com/uefachampionsleague/news/025a-0eaae578b071-3f2001de8325-1000--united-rocked-by-ronaldo/'),
26:('UEFA · resmi ilk 11 belgesi','https://www.uefa.com/newsfiles/UCL/2003/1065206_LU.pdf'),
}
MINUTES={1:['54′','56′','60′'],2:['6′','90+1′','90+3′'],7:['73′','90′','90+1′','95′'],13:['30′','86′','90′']}
PENS={1:[2,3],3:[6,5],22:[3,4],32:[5,3]}
EXTRA={1:120,3:120,4:120,7:120,22:120,32:120}
AGG={6:[6,5],7:[6,5],8:[3,3],9:[4,3],10:[5,4],11:[1,1],12:[2,3],16:[3,4],17:[4,4],19:[5,6]}
def build():
 matches=[]
 for n,line in enumerate(ROWS.splitlines(),1):
  date,h,a,stage,title,kind,answer,wrong,prompt,clock,score,story,hint,uefa=line.split('|')
  mid=f'ucl_{n:02}'; h,a=int(h),int(a); labels=answer.split(';')+(wrong.split(';') if wrong else [])
  opts=[{'id':hashlib.sha256(f'{mid}:{label}'.encode()).hexdigest()[:12],'label':label} for label in labels]
  keys=[o['id'] for o in opts[:len(answer.split(';'))]]
  random.Random(mid).shuffle(opts)
  if kind=='timeline' and [o['id'] for o in opts]==keys: opts.reverse()
  season=f'{int(date[:4])-1}/{date[:4]}' if int(date[5:7])<8 else f'{date[:4]}/{int(date[:4])+1}'
  row={'id':mid,'number':n,'season':season,'date':date,'round':stage,'title':title,'home':{'id':h,'name':CLUBS[h]},'away':{'id':a,'name':CLUBS[a]},'competition':'Avrupa Şampiyon Kulüpler Kupası' if n==25 else 'UEFA Şampiyonlar Ligi','type':kind,'prompt':prompt,'clock':clock,'hint':hint,'intro':f'{CLUBS[h]} ve {CLUBS[a]}, Avrupa sahnesinde karşı karşıya. Bu gecenin izini sür; belirleyici anı kendi bilginle keşfet.','options':opts,'answerKeys':keys,'result':{'answer':answer.replace(';',' → '),'score':score,'story':story,'penalties':PENS.get(n),'aggregate':AGG.get(n),'duration':EXTRA.get(n,90),'events':[{'label':label,'minute':MINUTES[n][i]} for i,label in enumerate(answer.split(';'))] if kind=='timeline' else [],'sources':[{'name':'UEFA · maç arşivi','url':f'https://www.uefa.com/uefachampionsleague/match/{uefa}/'}]},'verification':{'status':'reviewed','reviewedAt':'2026-10-10','statsBombMatchId':SB.get(n),'rawProviderDataIncluded':False}}
  if n in XI: row['lineup']={'club':XI[n][0],'rows':XI[n][1],'note':'Başlangıç 11’i · şematik yerleşim'}
  if n in SOURCE_OVERRIDES:
   name,url=SOURCE_OVERRIDES[n]; row['result']['sources']=[{'name':name,'url':url}]
  if n in XI and n!=25:
   row['result']['sources'].append({'name':'UEFA · finaller ve başlangıç kadroları','url':'https://editorial.uefa.com/resources/0282-18407a7a3056-fed61d05639b-1000/ucl_202223_finals_md13.pdf'})
  matches.append(row)
 catalog={'version':1,'matches':matches,'economy':{'match':{'coins':8,'xp':20},'milestones':[{'count':10,'coins':40,'xp':75},{'count':20,'coins':70,'xp':100},{'count':34,'coins':100,'xp':150}]}}
 (ROOT/'functions/config/ucl_catalog.json').write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
 export(catalog)
def export(catalog):
 public={**catalog,'matches':[{k:v for k,v in m.items() if k not in ('answerKeys','result','verification')} for m in catalog['matches']]}
 (ROOT/'assets/data/ucl_moments_v2.json').write_text(json.dumps(public,ensure_ascii=False,indent=2)+'\n')
if __name__=='__main__': build()
