"""Reviewed What If story pack. Alternate transfers are fiction, never reported deals."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
S = {
 'psg':'https://en.news.psg.fr/press-releases/first-team/leo-messi-signs-for-paris-saint-germain',
 'kdb':'https://www.mancity.com/news/first-team/first-team-news/2015/august/kevin-de-bruyne-signs-for-manchester-city',
 'salah':'https://www.liverpoolfc.com/news/first-team/266595-liverpool-fc-complete-signing-of-mohamed-salah',
 'toure':'https://www.mancity.com/news/first-team/first-team-news/archive/2010/july/manchester-city-sign-yaya-toure',
 'giuseppe':'https://www.inter.it/en/archivio_giocatore/G0038/giuseppe-baresi',
 'cech':'https://www.arsenal.com/news/news-archive/20151215/cech-i-thought-record-was-impossible',
 'barca':'https://www.fcbarcelona.com/en/club/history/legendary-players',
 'united':'https://www.manutd.com/en/club/history/history-by-decade/2000-2009',
 'zidane':'https://www.realmadrid.com/en-US/the-club/history/football-legends/zinedine-zidane',
 'stefano':'https://www.realmadrid.com/en-US/the-club/history/football-legends/alfredo-di-stefano-laulhe',
 'milan':'https://www.acmilan.com/en/club/legends/champions',
 'gerrard':'https://www.liverpoolfc.com/info/steven-gerrard',
 'drogba':'https://www.chelseafc.com/en/didier-drogba',
 'makelele':'https://www.chelseafc.com/en/claude-makelele',
 'lewa':'https://www.bundesliga.com/en/bundesliga/news/robert-lewandowski-borussia-dortmund-klopp-bayern-munich-barcelona-18081',
 'modric':'https://www.tottenhamhotspur.com/news/1042121/the-foe-you-know-real-madrids-modric-and-bale',
 'laudrup':'https://www.fcbarcelona.com/en/card/648078/michael-laudrup',
 'lukaku':'https://www.inter.it/en/news/2021-08-12-romelu-lukaku-to-chelsea-announcement',
 'ronaldo':'https://www.inter.it/en/archivio_giocatore/G0556',
 'sneijder':'https://www.uefa.com/uefachampionsleague/news/0205-0e82f5488bd6-736eb926ee25-1000--galatasaray-signal-intent-with-sneijder-signing/',
 'vanbasten':'https://www.acmilan.com/en/hall-of-fame/inductees/marco-van-basten',
 'maldini':'https://www.acmilan.com/en/club/legends/player/paolo-maldini',
}
def q(kind, prompt, labels, answer, hint, strong, explanation):
 return dict(type=kind,prompt=prompt,options=[dict(key=f'o{i}',label=v) for i,v in enumerate(labels)],answerKeys=[f'o{i}' for i in answer],hint=hint,strongHint=strong,explanation=explanation)
def choice(kind,prompt,right,wrong,hint,strong,explanation):
 return q(kind,prompt,[right,*wrong],[0],hint,strong,explanation)
def time(prompt,events,hint,strong,explanation):
 return q('timeline',prompt,events,list(range(len(events))),hint,strong,explanation)
rows=[]
def add(id,name,year,title,intro,real,alt,ending,fiction,tasks,source):
 rows.append(dict(id=id,name=name,year=year,title=title,intro=intro,
  routes=[dict(id='real',label=real,kind='history',ending=ending,task=tasks[0]),dict(id='alternate',label=alt,kind='fiction',ending=fiction,task=tasks[1])],
  sources=[dict(label='Tarihsel kayıt • '+k,url=S[k]) for k in source],
  editorialNote='Alternatif rota oyun için kurgulanmıştır; gerçekleşmiş teklif veya kesinleşmiş transfer iddiası değildir.'))
add('messi','Lionel Messi',2021,'Bir dönemin ardından',
 '2021 yazında Messi’nin uzun kulüp yolculuğunda bir sayfa kapandı. Yeni bir ülke, yeni takım arkadaşları ve farklı bir oyun düzeni gündeme geldi. Sen bu kırılma anının iki ihtimalini açacaksın. Kararın bir sınav değil; seçtiğin evrene geçmek için çözmen gereken futbol görevi seni bekliyor.',
 'Paris yolunu izle','Manchester City ihtimalini aç',
 'Messi 2021 yazında Paris Saint-Germain’e katıldı. Barcelona’daki uzun döneminin ardından Fransa’da yeni bir takım düzenine girdi. Bu rota gerçekleşen transferi izler. Oyundaki görevin cevabı ise ayrı bir kariyer bağlantısıdır; bir oyuncunun başka bir kulübe gitmesinin bütün sonuçlarını tek başına açıklamaz.',
 'Bu evrende Messi, Manchester City’de Guardiola ile yeniden çalışabilirdi. Pas istasyonları, sahte dokuz rolü ve kanat oyuncularının koşuları farklı biçimde kurulabilirdi. Ancak yeni ligde uyum, takım dengesi ve sezonun koşulları sonucu değiştirirdi. Bu kurgu bir kupa ya da bireysel ödül garantisi değil, başka bir hücum düzenini hayal etme fırsatıdır.',
 [choice('connection','Barcelona ve PSG A takımlarında forma giymiş ismi seç.','Neymar',['Harry Kane','Marco Reus'],'Güney Amerika’dan gelen hücum oyuncularını düşün.','Brezilyalı bir hücumcu; iki kulüp arasında 2017’de geçiş yaptı.','Neymar Barcelona’dan 2017 yılında PSG’ye geçti.'),choice('connection','Barcelona ve Manchester City A takımlarında forma giymiş ismi seç.','Yaya Touré',['Paolo Maldini','Francesco Totti'],'Orta sahadaki fizik gücüyle tanınan bir isim.','Fildişi Sahilli orta saha, İngiltere’ye 2010’da geçti.','Yaya Touré Barcelona’dan Manchester City’ye 2010’da transfer oldu.')],['barca'])
add('cristiano','Cristiano Ronaldo',2003,'İlk büyük sıçrama',
 '2003’te Portekiz’de parlayan genç bir kanat oyuncusu Avrupa’nın dikkatini çekiyordu. Henüz kariyerinin sonraki dönemlerindeki golcü kimliğine ulaşmamıştı. Yeni bir ligde gelişmek, doğru antrenörle çalışmak ve süre bulmak belirleyici olacaktı. Burada gerçekleşen yol ile Londra’da kurduğumuz alternatif bir başlangıç arasında seçim yapabilirsin.',
 'Manchester United yolunu izle','Arsenal ihtimalini aç',
 'Cristiano Ronaldo 2003’te Sporting’den Manchester United’a geçti. Sir Alex Ferguson yönetiminde gelişti ve İngiltere döneminin ardından 2009’da Real Madrid’e transfer oldu. Arsenal rotası bu oyunda alternatif tarih olarak sunulur; sözleşme, forma baskısı veya anlaşmanın neden gerçekleşmediğine ilişkin kesin bir iddia taşımaz.',
 'Arsenal evreninde genç kanat, Wenger’in pas oyununda bire bir becerilerini geliştirebilirdi. Daha dar alanlarda verilecek kararlar ve takımın hücum hareketliliği onun rolünü başka yöne taşıyabilirdi. Aynı istatistikleri üreteceğini varsayamayız. Burada keşfettiğin şey, farklı bir futbol ortamının genç bir yeteneğin gelişimine nasıl başka sorular sorabileceğidir.',
 [choice('transfer','Ronaldo’yu 2003’te İngiltere’ye gelmeden önce yetiştiren kulüp hangisiydi?','Sporting',['Porto','Benfica'],'Lizbon’un iki büyük kulübünden biri.','Yeşil-beyaz renkleri düşün.','Ronaldo’nun profesyonel başlangıcı Sporting’di.'),choice('transfer','Arsenal’in 2003-04 sezonunda teknik direktörü kimdi?','Arsène Wenger',['José Mourinho','Rafael Benítez'],'Fransız teknik direktör.','Kulüpte 1996’da başlayan uzun bir görev dönemi var.','Wenger, Arsenal’in 2003-04 lig şampiyonluğunda teknik direktördü.')],['united'])
add('lewandowski','Robert Lewandowski',2010,'Yeni ligin eşiğinde',
 '2010’da Polonya’da yükselen bir golcü, kariyerini başka bir ligde sürdürmeye hazırlanıyordu. Bir sonraki takım, oyunun temposunu ve gelişim alanlarını değiştirecekti. Avrupa’ya açılan iki kapıyı düşün: Almanya’daki gerçek yol ve İngiltere’de hayal ettiğimiz rota. Popüler transfer anlatılarındaki ayrıntıları gerçekleşmiş anlaşma gibi kabul etmiyoruz.',
 'Dortmund yolunu izle','Blackburn ihtimalini aç',
 'Lewandowski 2010’da Lech Poznań’dan Borussia Dortmund’a katıldı. Klopp döneminde gelişti; 2014’te Bayern Münih’e geçti. Blackburn ihtimali bu oyunda karşılaştırma için kurulan alternatif rotadır. Uçuş sorunu veya başka tek bir olay, gerçekleşmeyen transferin tüm nedenlerini kesin biçimde açıklayan bilgi olarak kullanılmaz.',
 'Blackburn evreninde hava topları, ikinci toplar ve farklı savunma eşleşmeleri daha erken öne çıkabilirdi. Lewandowski’nin ceza sahası becerileri başka bir takımın ihtiyaçlarıyla şekillenebilirdi. Ancak bu başlangıç, sonraki transferlerini veya gol sayılarını garanti etmezdi. Hayali rota, aynı oyuncunun farklı bir öğrenme ortamında nasıl sınanabileceğini düşünmek için açılıyor.',
 [choice('connection','Dortmund ve Bayern Münih’te oynamış oyuncuyu seç.','Mats Hummels',['John Terry','Carles Puyol'],'Savunmanın merkezinde oynar.','Alman bir stoper.','Hummels her iki kulübün A takımında da forma giydi.'),choice('connection','Blackburn ve Manchester United formalarını giymiş oyuncuyu seç.','Andy Cole',['Xavi','Francesco Totti'],'1990’ların İngiliz santrforlarından biri.','1999’daki üç kupalı takımın hücumcularındandı.','Andy Cole, Manchester United ve Blackburn’de oynadı.')],['lewa','united'])
add('gerrard','Steven Gerrard',2005,'Kaptanın kavşağı',
 '2005 yazında Avrupa’nın en büyük sahnesinden gelen bir kaptan, kariyerinin yönünü düşünüyordu. Bir kulüple kurulan bağ ile yeni bir takımda kendini deneme fikri aynı soruda buluşuyor. Senin seçimin geçmişi değiştirmeyecek; bu oyunda gerçek rotayı izleyebilir veya başka bir orta saha düzeninin ihtimalini açabilirsin.',
 'Liverpool’da devam et','Chelsea ihtimalini aç',
 'Gerrard Liverpool’da kaldı ve kulübün kaptanı olarak uzun yıllar oynamayı sürdürdü. 2005 Şampiyonlar Ligi zaferi kariyerinin belirgin dönüm noktalarından biri olarak kaldı. Burada Liverpool yolu gerçek tarihi temsil eder. Chelsea’de oluşturduğumuz görev ise yalnız o dönemde gerçekten var olan kadro bilgisine dayanır.',
 'Chelsea evreninde Gerrard’ın ileri koşuları ile takımın mevcut orta saha görevleri yeniden paylaşılabilirdi. Topu kimin taşıdığı, ceza sahasına kimin girdiği ve gerideki alanı kimin koruduğu yeni kararlar gerektirirdi. Çok sayıda yıldızın bir araya gelmesi kusursuz uyum anlamına gelmez. Bu rota olası bir taktik dengeyi araştırır.',
 [choice('teammate','2005 Avrupa finalinde Gerrard ile aynı takımda oynayan orta sahayı seç.','Xabi Alonso',['Luka Modrić','Toni Kroos'],'İspanyol bir oyun kurucu.','Sonraki kariyerinde Madrid ve Münih durakları da var.','Xabi Alonso 2005 finalinde Liverpool kadrosundaydı.'),choice('teammate','2004-05 Chelsea kadrosunda bulunan orta sahayı seç.','Frank Lampard',['Steven Davis','Paul Scholes'],'Ceza sahasına yaptığı koşularla tanınır.','İngiliz milli takımında da oynayan bir orta saha.','Frank Lampard 2004-05 sezonunda Chelsea’deydi.')],['gerrard','makelele'])
add('neymar','Neymar',2017,'Üçlünün yol ayrımı',
 '2017 yazında dünya futbolunun konuştuğu bir karar, yıldızlarla dolu bir hücum hattının geleceğini değiştirdi. Yeni bir takımda merkezde olmak ile alışılan düzende kalmak farklı sorumluluklar getirebilirdi. Bu senaryoda kararını ver, sonra gerçek kariyerin sırasını çöz. Bir transferin bütün kulüp tarihini tek başına belirlediğini varsaymıyoruz.',
 'Paris’e geçişi izle','Barcelona’da kalmayı hayal et',
 'Neymar 2017’de Barcelona’dan PSG’ye geçti. Barcelona’daki 2013-2017 dönemi sona ererken yeni bir ligde kariyerine devam etti. Sonraki kulüp kararlarını yalnız bu ayrılığa bağlamak eksik olur. Bu gerçek rota, olayların doğrulanabilir sırasını gösterir; uzun vadeli bütün sonuçlar için tek neden ileri sürmez.',
 'Neymar’ın kaldığı evrende hücum üçlüsü birlikte çalışmayı sürdürebilirdi. Ancak rakiplerin uyumu, oyuncuların fiziksel durumu ve teknik kararlar yine belirleyici olurdu. Kadronun yenilenmesi tamamen durmayabilir, roller zaman içinde değişebilirdi. Bu son, kazanılmamış kupaları var saymak yerine tanıdık bir birlikteliğin bir sezon daha hangi sorularla karşılaşabileceğini hayal eder.',
 [time('Neymar’ın bu kulüp duraklarını ilk katıldığı tarihe göre sırala.',['Santos','Barcelona','PSG'],'Güney Amerika’dan Avrupa’ya uzanan çizgiyi izle.','İspanya dönemi Fransa döneminden önce.','Sıra Santos → Barcelona (2013) → PSG (2017).'),time('Neymar’ın bu olaylarını eskiden yeniye sırala.',['Barcelona’ya katılması','Barcelona ile 2015 Avrupa zaferi','PSG’ye geçmesi'],'Kupayı kazandığı kulüp dönemini yerleştir.','Avrupa zaferi iki transferin arasında.','2013’te katıldı, 2015’te Avrupa şampiyonu oldu, 2017’de ayrıldı.')],['barca'])
add('zidane','Zinedine Zidane',1996,'Yetenek için yeni sahne',
 '1996’da Fransız bir oyun kurucu Avrupa kariyerinde yeni bir sayfa açıyordu. Topa dokunuşu ve oyunu okuma biçimi farklı liglerde başka şekillerde kullanılabilirdi. Gerçek İtalya yolunu veya İngiltere’de kurguladığımız ihtimali seç. Söylentilerdeki çarpıcı sözleri kanıtlanmış transfer gerekçesi olarak kullanmadan, kariyerin gerçek duraklarından bir görev çözeceğiz.',
 'İtalya yolunu izle','Blackburn ihtimalini aç',
 'Zidane Bordeaux’dan 1996’da Juventus’a geçti; 2001’de Real Madrid’e katıldı. Bu rota kariyerinin gerçek kulüp sırasını temel alır. Blackburn ihtimali alternatif bir oyun sahnesidir. Yöneticilere atfedilen popüler sözler veya gerçekleşmeyen pazarlıklar, burada tarihsel kesinlik taşıyan bilgi ve doğru cevap olarak sunulmaz.',
 'Blackburn’de Zidane’ın pas temposu, doğrudan hücum alışkanlıklarıyla yeni bir ilişki kurabilirdi. Takımın topu ona hangi bölgede ulaştırdığı belirleyici olurdu. Yetenek aynı kalsa da çevresindeki koşular ve rakip baskısı farklılaşırdı. Bu evren, sonraki kariyerindeki başarıları otomatik olarak İngiltere’ye taşımıyor; bir oyun kurucunun yeni şartlara nasıl uyabileceğini tartışıyor.',
 [choice('missing','Bordeaux → ? → Real Madrid: boş durağı tamamla.','Juventus',['Lazio','Napoli'],'İtalya’da siyah-beyaz bir forma.','Torino kentini düşün.','Zidane Juventus’ta 1996-2001 arasında oynadı.'),choice('missing','Zidane’ın Juventus’tan önceki Fransız kulübü hangisiydi?','Bordeaux',['Lyon','Monaco'],'Ülkenin güneybatısındaki bir kulüp.','Şarap üretimiyle de tanınan bir kentin takımı.','Zidane Bordeaux’dan Juventus’a transfer oldu.')],['zidane'])
add('di_stefano','Alfredo Di Stéfano',1953,'Bir çağın başlangıcı',
 '1953’te Avrupa futbolunda yeni bir dönemin kapısı aralanıyordu. Bir yıldızın hangi formayı giyeceği iki büyük kulübün geleceğiyle birlikte konuşuldu. Karmaşık transfer sürecini tek bir siyasi nedene indirgemiyoruz. Burada gerçek kariyerin izini sürebilir veya başka bir forma altında açılan kurgusal yolu seçebilirsin.',
 'Madrid yolunu izle','Barcelona ihtimalini aç',
 'Di Stéfano 1953’te Real Madrid’e katıldı ve kulübün ilk beş Avrupa Kupası zaferinde önemli rol oynadı. Transfer sürecinde Barcelona da yer aldı. Bu karmaşık sürece dair tek taraflı bir hüküm vermiyoruz. Gerçek son yalnız gerçekleşen kulüp yolunu ve sonraki Avrupa başarılarını kayda geçirir.',
 'Barcelona evreninde hücumu yönlendiren hareketli bir yıldız, takımın pas ve koşu düzenini değiştirebilirdi. Madrid ve Barcelona farklı kadro kararları alabilirdi; fakat sonraki Avrupa kupalarının sonuçları bu seçimden hesaplanamaz. Bu rota başka bir sportif başlangıcı hayal eder. Gerçekte oynanmamış sezonları tarihsel kayıtla karıştırmadan, olası bir oyun kimliğini düşünmeni ister.',
 [choice('connection','Real Madrid ve Barcelona A takımlarında oynamış ismi seç.','Luís Figo',['Francesco Totti','Ryan Giggs'],'Portekizli bir kanat oyuncusu.','İki kulüp arasındaki geçişi 2000 yılında oldu.','Figo iki kulübün de A takımında oynadı.'),choice('connection','Barcelona ve Real Madrid formalarını giymiş teknik orta sahayı seç.','Michael Laudrup',['Paul Scholes','Steven Gerrard'],'Danimarkalı bir oyun kurucu.','1990’larda İspanya’da iki farklı büyük takımda oynadı.','Laudrup Barcelona’dan Real Madrid’e geçti.')],['stefano','laudrup'])
add('zlatan','Zlatan Ibrahimović',2001,'Kendi yolunu çizen genç',
 '2001’de İsveç’ten yükselen uzun boylu bir forvet Avrupa sahnesine adım atıyordu. Yeni bir kulüpte süre kazanmak, tekniğini geliştirmek ve oyun disiplinine uyum sağlamak gündemindeydi. Gerçek kariyer yoluna bakabilir veya Londra’da kurduğumuz alternatif başlangıcı seçebilirsin. Karardan sonra bir kulüp bilgisi görevi seni bekliyor.',
 'Hollanda yolunu izle','Arsenal ihtimalini aç',
 'Ibrahimović Malmö’den Ajax’a geçti ve sonraki yıllarda İtalya, İspanya, Fransa ile İngiltere’de oynadı. Burada Hollanda yolu gerçek başlangıcı temsil eder. Arsenal senaryosu bir anlaşmanın kesinleştiğini söylemez. Aktarılan deneme antrenmanı hikâyelerini doğrulama zorunluluğu olmayan dramatik ayrıntılar olarak oyunun doğru cevaplarına taşımıyoruz.',
 'Arsenal evreninde uzun bir santrforun tekniği, hareketli hücumcuların koşularıyla birleşebilirdi. Sırtı dönük oyun ile tek pas tercihleri arasında farklı bir denge kurulabilirdi. Genç bir oyuncunun gelişimi, süre bulmasına ve takımın ona alan açmasına bağlı olurdu. Bu ihtimal onun gerçek kariyerinin aynısını başka bir forma ile yaşayacağını vaat etmez.',
 [choice('transfer','Zlatan’ın Malmö’den sonra katıldığı kulüp hangisiydi?','Ajax',['PSV','Feyenoord'],'Amsterdam’daki kulübü düşün.','Genç yetenek geliştirmesiyle tanınan kırmızı-beyaz ekip.','Zlatan 2001’de Ajax’a transfer oldu.'),choice('transfer','2001’de Arsenal’in iç saha stadı hangisiydi?','Highbury',['Emirates Stadium','Wembley'],'Kulübün yeni stadından önceki evi.','2006’ya kadar kullanılan stat.','Arsenal 2001’de Highbury’de oynuyordu.')],['barca'])
add('rooney','Wayne Rooney',2010,'Şehrin iki yakası',
 '2010’da İngiliz bir yıldız kariyerinin devamına ilişkin bir yol ayrımındaydı. Aynı şehirdeki iki futbol projesi, sadakat ve yeni başlangıç sorularını düşündürüyor. Gerçek yolu seçebilir ya da komşu kulüpteki kurgusal ihtimali açabilirsin. Görevde hayali takım arkadaşlığı üretmeyeceğiz; o dönemin gerçek kadrolarına bakacağız.',
 'United’da devam et','Manchester City ihtimalini aç',
 'Rooney Manchester United’da kaldı ve sonraki yıllarda kulübün önemli oyuncularından biri olmaya devam etti. City seçeneği bu oyun için oluşturulmuş alternatif rotadır. Bir transferin tamamlandığını veya tek bir sebeple engellendiğini ileri sürmez. Kadro görevleri gerçek oyuncu birlikteliklerini, sonuç metni ise seçtiğin evreni anlatır.',
 'Şehrin diğer tarafında Rooney’nin hem santrfor hem bağlantı oyuncusu olarak kullanılabileceği farklı düzenler kurulabilirdi. Takımın hücum merkezinin paylaşılması yeni uyum sorunları da doğurabilirdi. Taraftar tepkisi veya gelecekteki kupalar hakkında kesin sonuç yazmıyoruz. Bu paralel evren, aynı şehirdeki farklı bir futbol projesinin oyuncuya hangi yeni roller açabileceğini düşünür.',
 [choice('teammate','2010-11 United kadrosunda Rooney ile oynayan kanat oyuncusunu seç.','Nani',['Eden Hazard','Gareth Bale'],'Portekizli bir kanat.','Sporting geçmişi var.','Nani 2010-11 sezonunda Manchester United kadrosundaydı.'),choice('teammate','2010-11 Manchester City kadrosundaki İspanyol oyun kurucu kimdi?','David Silva',['Andrés Iniesta','Xavi'],'Valencia’dan İngiltere’ye geçti.','Sol ayağıyla oyun kuran hücumcu.','David Silva 2010 yazında City’ye katıldı.')],['united'])
add('laudrup','Michael Laudrup',1983,'Kuzeyden açılan yol',
 '1983’te Danimarkalı bir yetenek kariyerini ülkesinin dışına taşımaya hazırlanıyordu. Farklı ligler aynı oyuncudan farklı roller isteyebilirdi. Gerçek İtalya çizgisini izle veya İngiltere’de başka bir başlangıç hayal et. Gerçekleşmeyen pazarlıkların ayrıntısını kesin bilgi saymadan, sonraki kariyerinin doğrulanabilir bir durağını bulacağız.',
 'İtalya çizgisini izle','Liverpool ihtimalini aç',
 'Laudrup İtalya’da Lazio ve Juventus dönemlerini yaşadı; 1989’da Barcelona’ya katıldı. Bu rota onun gerçekleşen kulüp yolculuğunu temel alır. Liverpool seçeneği kurgusal karşılaştırmadır. Sonraki başarıları tek bir transfer kararına indirgemeden, farklı liglerde gelişen bir oyun kurucunun izlediği gerçek durakları birbirinden ayırıyoruz.',
 'Liverpool evreninde Laudrup’un dar alandaki pasları İngiliz futbolunun temposuyla buluşabilirdi. Fiziksel baskı altında boşluk bulmak ve takımın hareketliliğine uyum sağlamak farklı bir gelişim yolu açabilirdi. Bu senaryo gerçek kariyerindeki bütün kupaları buraya taşımaz. Teknik bir yeteneğin başka bir futbol kültüründe aynı sorulara nasıl farklı cevaplar verebileceğini hayal eder.',
 [choice('transfer','Laudrup 1989’da Barcelona’ya hangi kulüpten geldi?','Juventus',['Inter','Roma'],'İtalya’daki siyah-beyaz kulüp.','Torino’daki iki büyük takımdan biri.','Laudrup Juventus’tan Barcelona’ya geldi.'),choice('transfer','Laudrup’un 1983-85 arasında forma giydiği Roma kulübünü seç.','Lazio',['Napoli','Parma'],'Açık mavi formayı düşün.','Roma kentinin kartal simgeli kulübü.','Laudrup Juventus öncesinde Lazio’da oynadı.')],['laudrup'])
add('modric','Luka Modrić',2008,'Yeni ritim',
 '2008’de Hırvat bir orta saha oyuncusu daha yüksek tempolu bir lige geçmeye hazırlanıyordu. Topla sakin kalmak, baskıdan çıkmak ve oyunun hızını belirlemek onun için yeni sınavlar olacaktı. Londra’daki gerçek başlangıcı seçebilir veya kuzeydeki alternatif yolu açabilirsin. Görev, geleceği tahmin etmek yerine gerçek kariyerin boşluğunu tamamlatacak.',
 'Londra yolunu izle','Newcastle ihtimalini aç',
 'Modrić 2008’de Dinamo Zagreb’den Tottenham’a transfer oldu. İngiltere’de dört yıl oynadıktan sonra 2012’de Real Madrid’e geçti. Bu iki transfer gerçek kariyerin sınırlarını oluşturur. Newcastle rotası, aynı başlangıç koşullarının başka bir kulüpte nasıl farklı sorular üretebileceğine ilişkin bir oyun kurgusudur.',
 'Newcastle evreninde Modrić topu savunmadan hücuma taşıyan ana bağlantı haline gelebilirdi. Farklı kadro ve teknik ekip tercihleri ona daha fazla sorumluluk veya daha dar bir rol verebilirdi. Gelişimi önceden hesaplanamazdı. Bu son, gerçek kariyerindeki ödülleri başka bir kulübe mal etmek yerine yeni bir orta saha düzeninin ihtimalini açar.',
 [choice('missing','Dinamo Zagreb → ? → Real Madrid zincirindeki İngiliz kulübü hangisi?','Tottenham',['Everton','West Ham'],'Kuzey Londra’da beyaz forma.','Kulübün simgesinde bir horoz var.','Modrić 2008-2012 arasında Tottenham’da oynadı.'),choice('missing','Modrić İngiltere’ye hangi Hırvat kulübünden geldi?','Dinamo Zagreb',['Hajduk Split','Rijeka'],'Başkentteki kulüp.','Mavi forma ile tanınır.','Modrić Dinamo Zagreb’den İngiltere’ye geçti.')],['modric'])
add('baresi','Franco Baresi',1977,'Bir şehrin savunması',
 '1970’lerin sonunda genç bir savunmacı için profesyonel futbolun kapısı aralanıyordu. Aynı şehrin iki güçlü kimliği, başka türlü gelişebilecek bir kariyeri düşündürüyor. Gerçek yolu izle veya farklı renklerde bir başlangıç seç. Altyapı seçmelerine ilişkin popüler hikâyeleri kesin gerekçe yapmadan, gerçek kadrolardan bir bilgi soracağız.',
 'Milan yolunu izle','Inter ihtimalini aç',
 'Baresi’nin profesyonel kariyeri Milan ile özdeşleşti. Uzun yıllar takımın savunmasına liderlik etti; 1997’de kaptanlık bandını Paolo Maldini devraldı. Bu gerçek rota, kulüp kimliğini ve savunma birlikteliğini esas alır. Diğer Milano kulübündeki gelişim senaryosu ise tarihsel bir kayıt veya kesinleşmiş teklif değildir.',
 'Inter evreninde genç savunmacı başka bir teknik ekip ve farklı savunma ortaklarıyla yetişebilirdi. Liderliğinin ne zaman ortaya çıkacağı, hangi sistemde daha rahat oynayacağı değişebilirdi. Tek bir altyapı tercihiyle gelecekteki kupaları yeniden dağıtmıyoruz. Bu ihtimal, oyuncu kimliği ile kulüp kültürünün birbirini nasıl etkileyebileceğini düşünmek için kurgulanmıştır.',
 [choice('teammate','1990’larda Milan savunmasında Baresi ile birlikte oynayan ismi seç.','Paolo Maldini',['Javier Zanetti','Carles Puyol'],'Aynı kulüpte uzun bir kariyer sürdü.','Sol bek ve stoper olarak oynadı.','Baresi ve Maldini Milan savunmasında birlikte oynadı.'),choice('teammate','1980’lerde Inter’de oynayan, Franco’nun ağabeyi olan futbolcu kimdi?','Giuseppe Baresi',['Fabio Cannavaro','Alessandro Nesta'],'Aynı aileden bir savunmacı.','Adı G harfiyle başlar.','Giuseppe Baresi uzun yıllar Inter forması giydi.')],['maldini','milan'])
add('beckham','David Beckham',2003,'Yeni bir merkez',
 '2003 yazında İngiltere’nin tanınan bir yıldızı yeni bir futbol ortamına geçiyordu. Duran toplar, uzun paslar ve sahanın sağındaki üretkenliği farklı takımlarda başka roller kazanabilirdi. Gerçek İspanya yolunu veya diğer büyük kulüpteki hayali rotayı seç. Soruda transfer söylentisini değil, gerçek kariyerden bir bağlantıyı çözeceksin.',
 'Madrid yolunu izle','Barcelona ihtimalini aç',
 'Beckham 2003’te Manchester United’dan Real Madrid’e transfer oldu. Madrid’deki döneminin ardından kariyerini farklı liglerde sürdürdü. Barcelona yolu bu oyunda alternatif tarih olarak yer alır. Oyuncunun tanınırlığı kadar, yeni bir takımda görev paylaşımının ve saha içi uyumun da önem taşıdığı bir kırılma anıdır.',
 'Barcelona evreninde Beckham’ın uzun pasları ve duran topları farklı bir hücum yapısına hizmet edebilirdi. Kanat genişliği ile merkezdeki yaratıcılık arasındaki dağılım yeniden kurulabilirdi. Ancak takımın diğer transferleri ve teknik tercihleri de sonucu etkilerdi. Bu son, tek bir yıldızın gelişiyle bütün sportif geleceğin belirlenebileceğini varsaymayan bir olasılık hikâyesidir.',
 [choice('transfer','Beckham’ın 2003 öncesindeki İngiliz kulübünü seç.','Manchester United',['Liverpool','Tottenham'],'Manchester’daki kırmızı forma.','1999’da üç kupa kazanan kulüp.','Beckham United’dan Real Madrid’e geçti.'),choice('transfer','Beckham’ın 2007’de katıldığı ABD kulübü hangisiydi?','LA Galaxy',['Inter Miami','New York City'],'Los Angeles’ı düşün.','Kulübün adı gökyüzüyle ilgili.','Beckham 2007’de LA Galaxy’ye katıldı.')],['united'])
add('drogba','Didier Drogba',2004,'Yeni bir hücum fikri',
 '2004’te Fransa’da dikkat çeken güçlü bir santrfor, İngiltere’de yeni bir sayfa açmaya hazırlanıyordu. Top saklamak, savunmayı yıpratmak ve takım arkadaşlarına alan açmak onun farklı yönleriydi. Londra’nın iki ayrı oyun fikrini karşılaştır. Seçiminden sonra gerçek kulüp bağlantıları arasından tek bir oyuncuyu bulman yeterli olacak.',
 'Chelsea yolunu izle','Arsenal ihtimalini aç',
 'Drogba 2004’te Marseille’den Chelsea’ye transfer oldu ve kulübün önemli golcülerinden biri haline geldi. Arsenal senaryosu bu oyun için alternatif olarak kurulmuştur. Gerçek görev, kulüpler arasında oynamış başka bir futbolcuyu sorar. Bu bağlantı bir transfer teklifinin varlığını kanıtlamak için değil, futbol bilgisini sınamak için kullanılır.',
 'Arsenal evreninde Drogba’nın top saklama gücü, hızlı paslarla hücum eden bir takım için başka bir seçenek yaratabilirdi. Savunmayı meşgul ederken kanatlardan gelen koşulara alan açabilirdi. Fakat bu uyum kendiliğinden oluşmazdı; takım alışkanlıklarının da değişmesi gerekirdi. Bu son kesin başarı yerine farklı bir santrfor profilinin açabileceği taktik olasılıkları anlatır.',
 [choice('connection','Chelsea ve Arsenal A takımlarında oynamış kaleciyi seç.','Petr Čech',['Manuel Neuer','Gianluigi Buffon'],'Uzun süre koruyucu başlıkla oynadı.','Çekyalı bir kaleci.','Čech Chelsea’den Arsenal’e geçti.'),choice('connection','Arsenal ve Chelsea formalarını giymiş sol beki seç.','Ashley Cole',['Philipp Lahm','Jordi Alba'],'İngiliz milli takımında oynadı.','Londra’daki iki kulüp arasında 2006’da geçti.','Ashley Cole iki kulüpte de oynadı.')],['drogba'])
add('pirlo','Andrea Pirlo',2011,'Oyunun yönünü değiştirmek',
 '2011’de deneyimli bir oyun kurucu için yeni bir dönem başlıyordu. Savunmanın önünden pas dağıtmak ve maçın ritmini belirlemek farklı takım yapılarında başka anlamlar taşıyabilirdi. Gerçek rotayı izle veya aynı yaz başka bir kulüp hayal et. İlerlemen için kariyerindeki gerçek durakları sıraya koyman gerekecek.',
 'Torino yolunu izle','Başka bir lig hayal et',
 'Pirlo 2011’de Milan’dan Juventus’a geçti. İtalya’daki yeni döneminin ardından New York City’de oynadı. Bu sıralama gerçek kariyer kaydıdır. Alternatif rota ise gerçekleşmemiş bir lig değişimini düşünmek için açılır. Takım değişiminin tek başına bütün başarıları açıklamadığını, kadro ve teknik düzenin birlikte rol oynadığını unutmuyoruz.',
 'Başka bir ligde Pirlo’nun pas menzili, rakiplerin baskı biçimine farklı cevaplar aramak zorunda kalabilirdi. Takım arkadaşlarının onun çevresinde kurduğu koruma ve koşu düzeni önem kazanırdı. Bu evren hangi kulübün kesin teklif yaptığını iddia etmez. Ustalığı yerleşmiş bir oyun kurucunun farklı bir futbol kültüründe nasıl yeni çözümler bulabileceğini hayal eder.',
 [time('Pirlo’nun bu kulüp duraklarını ilk katıldığı tarihe göre sırala.',['Inter','Milan','Juventus'],'Milano yılları Torino’dan önce.','Mavi-siyah forma, kırmızı-siyah formadan önce.','Pirlo Inter, Milan ve Juventus’ta bu sırayla oynadı.'),time('Pirlo’nun bu üç dönemini eskiden yeniye sırala.',['Milan','Juventus','New York City'],'Avrupa’dan Amerika’ya uzanan yolu düşün.','Torino dönemi iki şehir arasında.','Pirlo Milan’dan Juventus’a, ardından New York City’ye geçti.')],['milan'])
add('shearer','Alan Shearer',1996,'Eve giden yol',
 '1996’da İngiliz bir golcü kariyerinin en önemli kararlarından birine yaklaşıyordu. Bir kulübün hücumunu taşımak ile başka bir büyük projeye katılmak farklı beklentiler yaratacaktı. Gerçek kuzey yolunu seç veya Manchester’da kurguladığımız ihtimali aç. Görevde popüler pazarlık hikâyeleri yerine gerçek kariyer sırasını kullanacağız.',
 'Newcastle yolunu izle','United ihtimalini aç',
 'Shearer 1996’da Blackburn’den Newcastle United’a geçti. Premier League’deki gollerini Blackburn ve Newcastle formalarıyla biriktirdi. Manchester United rotası bu oyunda alternatif bir kariyer ihtimalidir. Gerçek son transferin gerçekleşen yönünü kaydeder; tercihlerin bütün kişisel ve sportif nedenlerini tek cümleye indirgemeye çalışmaz.',
 'Manchester evreninde Shearer’ın ceza sahası bitiriciliği farklı kanat servisleri ve hücum ortaklarıyla buluşabilirdi. Gol yükünün paylaşılması ve takım içi roller başka biçimde kurulabilirdi. Gerçekte kazanılmış kupaları bu hayali kadroya otomatik olarak yazamayız. Bu olasılık, bir golcünün alışkanlıklarının farklı bir takımın oyun planına nasıl uyabileceğini düşünmek için açılır.',
 [choice('missing','Southampton → ? → Newcastle: eksik kulübü bul.','Blackburn',['Everton','Aston Villa'],'1994-95 lig şampiyonunu düşün.','Mavi-beyaz parçalı forma.','Shearer Blackburn’den Newcastle’a geçti.'),choice('missing','Shearer’ın Blackburn’den önceki A takım durağı hangisiydi?','Southampton',['Portsmouth','Sunderland'],'İngiltere’nin güney kıyısında.','Azizler lakabıyla tanınır.','Shearer’ın ilk profesyonel kulübü Southampton’dı.')],['united'])
add('van_basten','Marco van Basten',1993,'Yarım kalan hareket',
 '1993’te bir golcünün kariyerinde sağlık sorunları giderek daha belirleyici hale geliyordu. Sahada yaptığı hareketlerle hatırlanan bir oyuncunun devam edememesi, futbolseverlere başka ihtimalleri düşündürür. Burada yaşanan gerçek yolu okuyabilir veya sağlıklı devam edebildiği bir kurgu açabilirsin. Görev, tıbbi tahminlere değil futbol tarihinin sırasına dayanır.',
 'Gerçek kariyeri izle','Sağlıklı devamı hayal et',
 'Van Basten’in son resmi maçları 1993’e uzanır; futbolu bıraktığını 1995’te açıkladı. Milan’daki golleri ve Hollanda ile 1988 Avrupa şampiyonluğu kariyerinin güçlü izleri arasında kaldı. Bu son gerçek zaman çizgisini anlatır. Sağlıklı kalsaydı ne kadar oynayacağı veya kaç gol atacağı hesaplanmış bir gerçek değildir.',
 'Bu evrende Van Basten bir süre daha sahada kalabilirdi. Milan hücumunda deneyimini yeni oyunculara aktarabilir, bitiriciliğiyle farklı maç planlarının parçası olabilirdi. Ancak yaş, kadro dönüşümü ve rekabet yine etkili olurdu. Bu kurgu tıbbi bir öngörü sunmaz; kaçırılan maçları kesin gollere veya kazanılmamış kupalara dönüştürmeden bir devam ihtimalini düşünür.',
 [time('Van Basten’in bu olaylarını eskiden yeniye sırala.',['Milan’a transfer','Hollanda ile 1988 Avrupa zaferi','1995’te emekliliğini açıklaması'],'Kulüp değişikliği milli takım zaferinden önce.','İtalya başlangıcı 1987’ye uzanır.','Milan 1987, Avrupa zaferi 1988, emeklilik açıklaması 1995.'),time('Bu kariyer evrelerini sırala.',['Ajax A takımı','Milan A takımı','Futbolu bırakma açıklaması'],'Hollanda’dan İtalya’ya giden yolu düşün.','İtalya dönemi gençlik kulübünden sonra.','Van Basten Ajax’tan Milan’a geçti, 1995’te emekliliğini açıkladı.')],['vanbasten'])
add('ronaldo_nazario','Ronaldo Nazário',2000,'Geri dönüş ihtimali',
 '2000’de büyük bir yıldızın kariyerinde ağır sakatlıklar önemli bir kesinti yaratmıştı. Sahaya dönüş, yalnız yetenek değil zaman ve yeniden uyum da gerektiriyordu. Gerçek kariyerin izini sürebilir veya bu kesintinin yaşanmadığı bir futbol evreni açabilirsin. Görevimiz hayali performans hesaplamak değil, dönemin gerçek kadrosunu tanımak.',
 'Gerçek geri dönüşü izle','Kesintisiz kariyeri hayal et',
 'Ronaldo’nun Inter dönemi 1997-2002 arasındaydı ve sakatlıklarla kesintiye uğradı. Sonrasında 2002 Dünya Kupası’nda Brezilya ile şampiyonluk yaşadı ve Real Madrid’e geçti. Bu sonuç yaşanmış kariyeri anlatır. Sakatlık olmasaydı aynı transferlerin, maçların veya bireysel başarıların gerçekleşeceğini varsaymak mümkün değildir.',
 'Kesintisiz evrende Ronaldo, Inter’de hücum ortaklarıyla daha uzun süre birlikte oynayabilirdi. Savunmaların onun hızına karşı aldığı önlemler ve takımın geliştirdiği çözümler değişebilirdi. Yine de belirli gol sayıları veya garanti şampiyonluklar yazmıyoruz. Bu kurgu sağlık hakkında bir tahmin değil, önemli bir oyuncunun sahada daha çok bulunmasının açabileceği futbol ihtimalleridir.',
 [choice('teammate','1999-2000 Inter kadrosunda Ronaldo ile bulunan İtalyan santrforu seç.','Christian Vieri',['Francesco Totti','Alessandro Del Piero'],'Güçlü fiziği ve sol ayağıyla tanınır.','Bobo lakabını düşün.','Vieri 1999’da Inter’e katıldı ve Ronaldo ile aynı kadroda yer aldı.'),choice('teammate','1997-98 Inter kadrosunda Ronaldo ile oynayan Arjantinli sağ beki seç.','Javier Zanetti',['Cafu','Roberto Carlos'],'Uzun yıllar Inter kaptanlığı yaptı.','Forma numarası 4’tü.','Zanetti ve Ronaldo 1997-98 Inter kadrosundaydı.')],['ronaldo'])
add('makelele','Claude Makélélé',2003,'Görünmeyen denge',
 '2003’te yıldızlarla dolu bir takımın orta sahasında önemli bir değişim yaşandı. Topu kazanan, alanı kapatan ve diğer oyunculara hareket özgürlüğü sağlayan rol yeniden tartışılıyordu. Gerçek ayrılık yolunu izle veya aynı düzenin sürdüğü bir evren aç. Bir takımın sonraki bütün sonuçlarını tek oyuncunun varlığına bağlamayacağız.',
 'Chelsea yolunu izle','Madrid’de kalmayı hayal et',
 'Makélélé 2003’te Real Madrid’den Chelsea’ye transfer oldu. Savunma önündeki rolü yeni takımının orta saha yapısında önemli yer tuttu. Madrid’in sonraki sonuçlarını yalnız bu ayrılığa bağlamak eksik bir açıklama olur. Gerçek rota transferi kaydeder; alternatif son ise aynı görev dağılımı sürseydi nelerin değişebileceğini düşünür.',
 'Madrid’de kalınan evrende yıldız hücumcuların arkasındaki alan paylaşımı daha farklı korunabilirdi. Ancak bütün takımın savunma davranışı tek bir oyuncudan ibaret olmazdı. Teknik ekip, kadro yaşı ve rakiplerin oyun planları yine sonucu etkilerdi. Bu son, kazanılmamış kupalar ilan etmek yerine görünmeyen bir orta saha rolünün takım dengesine olası katkısını anlatır.',
 [choice('teammate','2004-05 Chelsea’de Makélélé ile birlikte oynayan savunmacıyı seç.','John Terry',['Sergio Ramos','Nemanja Vidić'],'İngiliz bir stoper.','Chelsea’nin uzun süreli kaptanlarından.','Terry o sezon Chelsea savunmasının merkezindeydi.'),choice('teammate','2002-03 Real Madrid’de Makélélé ile birlikte oynayan Fransız oyun kurucuyu seç.','Zinedine Zidane',['Franck Ribéry','Robert Pirès'],'2001’de İtalya’dan İspanya’ya geçti.','2002 Avrupa finalindeki volesiyle de hatırlanır.','Zidane ve Makélélé 2002-03 Real Madrid kadrosundaydı.')],['makelele','zidane'])
add('chelsea_duo','De Bruyne & Salah',2014,'Gençliğe açılan alan',
 '2014 döneminde Chelsea’nin kadro kararları gelecekte başka takımlarda parlayacak iki oyuncuyu da kapsıyordu. Gelişim, süre bulma ve farklı liglerde deneyim kazanma birbirine bağlı konulardı. Gerçek kariyer ayrımlarını izle veya iki yeteneğe daha uzun süre alan açılan bir kulüp projesi hayal et. Görevde gerçek bağlantıları kullanacağız.',
 'Gerçek ayrılık yollarını izle','İki yeteneği elde tutmayı hayal et',
 'De Bruyne Chelsea sonrasında Wolfsburg ve Manchester City’de oynadı. Salah ise İtalya’daki döneminin ardından Liverpool’a geçti. İki oyuncunun sonraki gelişimini yalnız eski kulüplerinin kararıyla açıklayamayız. Bu gerçek son ayrı kariyer yollarını kaydeder; aynı takımda kalsalardı bugünkü başarılarının aynısını yaşayacaklarını ileri sürmez.',
 'Bu evrende Chelsea genç hücumculara daha fazla süre ve belirli roller verebilirdi. Ancak aynı anda gelişmek, kadro rekabetini ve takımın savunma dengesini yönetmeyi gerektirirdi. Sonraki kariyerlerinden bildiğimiz bütün özellikler aynı hızda ortaya çıkmayabilirdi. Bu kurgu yıldızları bir araya getirip kupaları peşinen dağıtmaz; gelişim için yaratılabilecek farklı koşulları düşünür.',
 [choice('connection','Chelsea ve Liverpool formalarını giymiş İspanyol santrforu seç.','Fernando Torres',['David Villa','Raúl'],'Atlético Madrid geçmişi var.','El Niño lakabıyla tanınır.','Torres Liverpool ve Chelsea’de oynadı.'),choice('connection','Chelsea ve Manchester City formalarını giymiş İngiliz orta sahayı seç.','Frank Lampard',['Paul Scholes','Steven Gerrard'],'Golcü bir orta saha oyuncusu.','City’de 2014-15 sezonunda oynadı.','Lampard uzun Chelsea döneminin ardından City’de oynadı.')],['drogba','makelele'])
add('de_gea','David de Gea',2015,'Son günün belirsizliği',
 '2015 yazının son transfer günlerinde bir kalecinin geleceği yoğun biçimde konuşuluyordu. Süreç tamamlanmadı ve kariyer başka bir yönde devam etti. Popüler tek cümlelik açıklamalar bütün ayrıntıları anlatmaz. Gerçek yolu izle veya İspanya’daki alternatif başlangıcı seç; görevde belgelenmiş futbol bilgisini kullanacağız, teknik arızayı kesin neden ilan etmeyeceğiz.',
 'Manchester’da devam et','Madrid ihtimalini aç',
 'De Gea’nın 2015’te Real Madrid’e transferi tamamlanmadı ve Manchester United’daki kariyeri devam etti. Bu olayın tek nedenini bozuk bir faks olarak sunmuyoruz. Gerçek rota gerçekleşen sonucu kaydeder. Alternatif rota ise transfer olsaydı yaşanabilecek uyum sürecini düşünür; tamamlanmamış bir anlaşmayı gerçekleşmiş gibi anlatmaz.',
 'Madrid evreninde De Gea farklı bir savunma hattıyla iletişim kurmak ve yeni beklentilere uyum sağlamak zorunda kalabilirdi. Ayağıyla oyun kurma tercihleri ve ceza sahası yönetimi başka bir sistemde değerlendirilebilirdi. Bir kaleci değişikliği sonraki bütün kupaları açıklamazdı. Bu olasılık hikâyesi, gerçekleşmeyen transferin kesin sportif sonucunu bildiğini iddia etmez.',
 [choice('transfer','De Gea 2011’de United’a hangi kulüpten geldi?','Atlético Madrid',['Sevilla','Valencia'],'İspanya başkentindeki kırmızı-beyaz ekip.','Kulüp adında Atlético geçer.','De Gea Atlético Madrid’den Manchester United’a geçti.'),choice('transfer','2014’te Real Madrid’e katılan Kosta Rikalı kaleci kimdi?','Keylor Navas',['Jan Oblak','Thibaut Courtois'],'2014 Dünya Kupası’nda dikkat çekti.','Levante’den transfer edildi.','Navas 2014’te Levante’den Real Madrid’e katıldı.')],['united'])
add('sneijder','Wesley Sneijder',2010,'Bir yılın iki yorumu',
 '2010’da kulüp ve milli takım düzeyindeki büyük başarılar bireysel ödüllerin nasıl değerlendirildiğini yeniden tartıştırdı. Takım kupaları ile bir oyuncunun sezon boyunca etkisi aynı şey değildir. Gerçek sonucu inceleyebilir veya farklı bir ödül kararını hayal edebilirsin. Görev öznel bir hak ediş yarışı değil, gerçek kariyerin zaman sırasıdır.',
 'Gerçek ödül sonucunu izle','Farklı kazananı hayal et',
 '2010 Ballon d’Or ödülünü Lionel Messi kazandı; Sneijder Inter ile üç kupa kazanılan sezonun önemli isimlerindendi ve Hollanda ile Dünya Kupası finaline çıktı. Ödülün kime verilmesi gerektiği bir değerlendirmedir. Bu gerçek son sonucu kaydeder, farklı görüşleri skandal veya kanıtlanmış haksızlık diye etiketlemez.',
 'Bu evrende bireysel ödül Sneijder’e verilebilirdi. Böyle bir karar o yılın başarılarının hatırlanma biçimini değiştirebilir, takım kupaları ile bireysel etkinin nasıl tartıldığına ilişkin başka bir anlatı kurabilirdi. Ancak geçmiş maç sonuçları değişmezdi. Bu kurgu, bir futbolcunun değerini tek ödüle indirmeden farklı bir değerlendirme ihtimalini görünür kılar.',
 [time('Sneijder’in bu kulüp duraklarını sırala.',['Real Madrid','Inter','Galatasaray'],'İspanya’dan İtalya’ya, ardından Türkiye’ye.','Milano dönemi ortada.','2009’da Inter’e, 2013’te Galatasaray’a geçti.'),time('Bu olayları eskiden yeniye sırala.',['Inter’e katılması','Inter ile 2010 Avrupa zaferi','Galatasaray’a transferi'],'Kulübe katılmadan onunla kupa kazanamaz.','Türkiye’ye geçiş Avrupa zaferinden sonra.','Inter’e 2009’da katıldı, 2010’da Avrupa şampiyonu oldu, 2013’te Türkiye’ye geldi.')],['sneijder'])
add('lukaku','Romelu Lukaku',2021,'Birlikte devam etmek',
 '2021 yazında şampiyon bir takımın hücumundaki önemli isim için yeni bir karar zamanı geldi. Tanıdık bağlantıları sürdürmek ile başka bir ligde yeniden kendini göstermek farklı beklentiler yaratacaktı. Gerçek ayrılık yolunu seç veya aynı formayla devam edilen bir evren aç. Görev gerçek kariyer çizgisindeki eksik durağı bulduracak.',
 'Londra’ya dönüşü izle','Inter’de kalmayı hayal et',
 'Lukaku 2021 yazında Inter’den Chelsea’ye transfer oldu. Inter’in 2020-21 lig şampiyonluğunda yer aldıktan sonra İngiltere’ye döndü; 2022’de kiralık olarak yeniden Inter’e katıldı. Bu rota gerçekleşen hareketleri birbirinden ayırır. Kalma seçeneği ise sonraki sezonun nasıl biteceğine dair kesin bir tahmin değildir.',
 'Inter’de kalınan evrende Lukaku tanıdığı hücum bağlantılarını sürdürebilirdi. Teknik ekipteki ve kadrodaki diğer değişiklikler yine yeni uyum gerektirecekti. Geçmiş şampiyonluk bir sonraki sezonun garantisi olmazdı. Bu hikâye, birlikte oynama alışkanlığının korunmasının olası avantajlarını düşünürken rekabetin, fiziksel durumun ve takım kararlarının sonucu değiştirebileceğini açık bırakır.',
 [choice('missing','Lukaku’nun 2019’da Inter’e gelmeden önceki kulübünü bul.','Manchester United',['Arsenal','Liverpool'],'Manchester’daki kırmızı forma.','Old Trafford’da oynayan kulüp.','Lukaku 2019’da United’dan Inter’e geçti.'),choice('missing','Lukaku’nun 2014-2017 arasında kalıcı olarak oynadığı Liverpool şehri kulübü hangisi?','Everton',['Liverpool','Tranmere Rovers'],'Mavi formayı düşün.','Goodison Park ile özdeşleşen kulüp.','Lukaku 2014’te Everton’a kalıcı transfer oldu.')],['lukaku'])
add('ronaldinho','Ronaldinho',2003,'Oyuna gelen gülümseme',
 '2003’te Brezilyalı bir yıldız yeni bir takımın hücumuna hayal gücü katmaya hazırlanıyordu. Beklenmedik paslar ve bire bir becerisi başka futbol kültürlerinde farklı roller kazanabilirdi. Gerçek İspanya yolunu veya İngiltere’de açtığımız hayali ihtimali seç. Transfer söylentilerinin ayrıntısı yerine gerçekleşmiş bir kariyer bilgisinden ilerleyeceğiz.',
 'Barcelona yolunu izle','United ihtimalini aç',
 'Ronaldinho 2003’te PSG’den Barcelona’ya katıldı. İspanya’daki dönemi kulübün önemli bir yenilenme süreciyle birlikte hatırlanır. Manchester United rotası bu oyunda alternatif tarih olarak açılır. Gerçekleşmeyen görüşmelerin tek bir nedenle sonuçlandığını iddia etmiyoruz; oyuncunun gerçek kariyer durağını ve kurgusal ihtimalini açıkça ayırıyoruz.',
 'Manchester evreninde Ronaldinho’nun yaratıcılığı hızlı kanat koşuları ve farklı bir hücum temposuyla buluşabilirdi. Topu ayağında tutma süresi ile takımın doğrudan oyun tercihleri arasında yeni bir denge aranabilirdi. Bu ihtimal başka bir oyuncunun gelişimini ya da gelecekteki kupaları kesin biçimde değiştirmiş sayılmaz. Yalnız başka bir futbol birlikteliğinin mümkün görüntüsünü kurar.',
 [choice('transfer','Ronaldinho 2003’te Barcelona’ya hangi kulüpten geldi?','PSG',['Lyon','Marseille'],'Fransa’nın başkentindeki kulüp.','Kırmızı ve mavi renkler.','Ronaldinho PSG’den Barcelona’ya geçti.'),choice('transfer','Ronaldinho’nun Brezilya’daki ilk profesyonel kulübünü seç.','Grêmio',['Santos','Flamengo'],'Porto Alegre kentini düşün.','Mavi, siyah ve beyaz renkleri kullanır.','Ronaldinho profesyonel kariyerine Grêmio’da başladı.')],['barca'])
chapters=[dict(id=i+1,title=t,subtitle=s) for i,(t,s) in enumerate([
 ('Kaçan Fırsatlar','Bir imza, başka bir başlangıç.'),('Alternatif Kaderler','Aynı yetenek, başka bir yol.'),('Yeniden Yazılan Tarih','Değişseydi ne olurdu?')])]
for i,r in enumerate(rows):
 r['chapter']=i//8+1
 for route in r['routes']:
  route['task']['id']=r['id']+'__'+route['id']
for r in rows:
 if r['id']=='messi':r['sources'].append(dict(label='PSG • 10 Ağustos 2021 transfer duyurusu',url=S['psg']))
 if r['id']=='messi':r['sources'].append(dict(label='Manchester City • Yaya Touré transferi',url=S['toure']))
 if r['id']=='baresi':r['sources'].append(dict(label='Inter • Giuseppe Baresi arşivi',url=S['giuseppe']))
 if r['id']=='drogba':r['sources'].append(dict(label='Arsenal • Petr Čech kariyeri',url=S['cech']))
 if r['id']=='chelsea_duo':r['sources']=[dict(label='Resmî transfer kaydı • '+key,url=S[key]) for key in ['kdb','salah']]
pack=dict(version=1,chapters=chapters,scenarios=rows)
assert len(rows)==24
for target in ['assets/data/what_if_v2.json','functions/config/what_if_catalog.json']:
 (ROOT/target).write_text(json.dumps(pack,ensure_ascii=False,indent=2)+'\n')
print('24 scenarios, 48 route tasks and endings written.')
