import 'achievement_models.dart';

class AchievementCatalog {
  AchievementCatalog._();

  static const int version = 2;

  static const List<AchievementDefinition> all = [
    AchievementDefinition(
      id: 'first_whistle',
      title: 'İlk Düdük',
      description: 'İlk dereceli maçını tamamla.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.bronze,
      signal: 'ranked_played',
      target: 1,
      iconKey: 'first_whistle',
    ),
    AchievementDefinition(
      id: 'first_victory',
      title: 'İlk Zafer',
      description: 'İlk dereceli galibiyetini al.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.bronze,
      signal: 'ranked_wins',
      target: 1,
      iconKey: 'first_victory',
    ),
    AchievementDefinition(
      id: 'challenger_10',
      title: 'Meydan Okuyucu',
      description: '10 dereceli maç tamamla.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.bronze,
      signal: 'ranked_played',
      target: 10,
      iconKey: 'challenger',
    ),
    AchievementDefinition(
      id: 'loyal_rival_50',
      title: 'Sadık Rakip',
      description: '50 dereceli maç tamamla.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.silver,
      signal: 'ranked_played',
      target: 50,
      iconKey: 'loyal_rival',
    ),
    AchievementDefinition(
      id: 'centurion_100',
      title: 'Yüzler Kulübü',
      description: '100 dereceli maç tamamla.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.gold,
      signal: 'ranked_played',
      target: 100,
      iconKey: 'centurion',
    ),
    AchievementDefinition(
      id: 'winner_10',
      title: 'Formda Günler',
      description: '10 dereceli galibiyet kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.bronze,
      signal: 'ranked_wins',
      target: 10,
      iconKey: 'form_days',
    ),
    AchievementDefinition(
      id: 'winner_50',
      title: 'Cesur Yürek',
      description: '50 dereceli galibiyet kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.silver,
      signal: 'ranked_wins',
      target: 50,
      iconKey: 'brave_heart',
    ),
    AchievementDefinition(
      id: 'winner_100',
      title: 'Zafer Makinesi',
      description: '100 dereceli galibiyet kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.gold,
      signal: 'ranked_wins',
      target: 100,
      iconKey: 'victory_machine',
    ),
    AchievementDefinition(
      id: 'streak_3',
      title: 'Isınan Motor',
      description: '3 dereceli maçı üst üste kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.bronze,
      signal: 'best_win_streak',
      target: 3,
      iconKey: 'hot_streak',
    ),
    AchievementDefinition(
      id: 'streak_5',
      title: 'Seri Katili',
      description: '5 dereceli maçı üst üste kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.silver,
      signal: 'best_win_streak',
      target: 5,
      iconKey: 'streak_killer',
    ),
    AchievementDefinition(
      id: 'streak_10',
      title: 'Değişmez Şampiyon',
      description: '10 dereceli maçı üst üste kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.gold,
      signal: 'best_win_streak',
      target: 10,
      iconKey: 'unchanged_champion',
    ),
    AchievementDefinition(
      id: 'elo_1100',
      title: 'Yükselen Yıldız',
      description: 'En az 1100 Elo seviyesine ulaş.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.bronze,
      signal: 'peak_elo',
      target: 1100,
      iconKey: 'rising_star',
    ),
    AchievementDefinition(
      id: 'elo_1250',
      title: 'Zor Lokma',
      description: 'En az 1250 Elo seviyesine ulaş.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.silver,
      signal: 'peak_elo',
      target: 1250,
      iconKey: 'tough_opponent',
    ),
    AchievementDefinition(
      id: 'elo_1400',
      title: 'Sıralama Canavarı',
      description: 'En az 1400 Elo seviyesine ulaş.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.gold,
      signal: 'peak_elo',
      target: 1400,
      iconKey: 'ranking_beast',
    ),
    AchievementDefinition(
      id: 'elo_1600',
      title: 'Efsaneler Arasına Katıl',
      description: 'En az 1600 Elo seviyesine ulaş.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.platinum,
      signal: 'peak_elo',
      target: 1600,
      iconKey: 'legend',
    ),
    AchievementDefinition(
      id: 'shared_xi_master',
      title: 'Ortak XI Ustası',
      description: 'Dereceli Ortak XI modunda 10 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.silver,
      signal: 'ranked_shared_xi_wins',
      target: 10,
      iconKey: 'shared_xi_master',
    ),
    AchievementDefinition(
      id: 'grid_master',
      title: 'Grid Ustası',
      description: 'Dereceli Grid modunda 10 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.silver,
      signal: 'ranked_grid_wins',
      target: 10,
      iconKey: 'grid_master',
    ),
    AchievementDefinition(
      id: 'cinko_master',
      title: 'Çinko Ustası',
      description: 'Dereceli Çinko modunda 10 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.silver,
      signal: 'ranked_cinko_wins',
      target: 10,
      iconKey: 'cinko_master',
    ),
    AchievementDefinition(
      id: 'five_master',
      title: 'Beşli Ustası',
      description: 'Dereceli Rastgele Beş modunda 10 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.silver,
      signal: 'ranked_five_wins',
      target: 10,
      iconKey: 'five_master',
    ),
    AchievementDefinition(
      id: 'daily_first',
      title: 'Takvim Çaylağı',
      description: 'İlk Günlük Mücadele sonucunu kaydet.',
      category: AchievementCategory.daily,
      tier: AchievementTier.bronze,
      signal: 'daily_days',
      target: 1,
      iconKey: 'calendar_rookie',
    ),
    AchievementDefinition(
      id: 'daily_7',
      title: 'Takvim Müdavimi',
      description: '7 farklı günde Günlük Mücadele oyna.',
      category: AchievementCategory.daily,
      tier: AchievementTier.bronze,
      signal: 'daily_days',
      target: 7,
      iconKey: 'calendar_regular',
    ),
    AchievementDefinition(
      id: 'daily_30',
      title: 'Ayın Taktisyeni',
      description: '30 farklı günde Günlük Mücadele oyna.',
      category: AchievementCategory.daily,
      tier: AchievementTier.gold,
      signal: 'daily_days',
      target: 30,
      iconKey: 'month_tactician',
    ),
    AchievementDefinition(
      id: 'daily_streak_7',
      title: 'Sadık Taktisyen',
      description: 'Günlük Mücadelede 7 günlük seri yap.',
      category: AchievementCategory.daily,
      tier: AchievementTier.silver,
      signal: 'best_daily_streak',
      target: 7,
      iconKey: 'loyal_tactician',
    ),
    AchievementDefinition(
      id: 'daily_perfect',
      title: 'Mükemmeliyetçi',
      description: 'Bir Günlük Mücadeleyi %100 başarıyla tamamla.',
      category: AchievementCategory.daily,
      tier: AchievementTier.gold,
      signal: 'perfect_daily_count',
      target: 1,
      iconKey: 'perfectionist',
    ),
    AchievementDefinition(
      id: 'weekly_5',
      title: 'Haftanın Savaşçısı',
      description: 'Aynı haftada 5 farklı gün skor kaydet.',
      category: AchievementCategory.daily,
      tier: AchievementTier.silver,
      signal: 'weekly_days',
      target: 5,
      iconKey: 'week_warrior',
    ),
    AchievementDefinition(
      id: 'first_friend',
      title: 'Takım Ruhu',
      description: 'İlk Linkball arkadaşını ekle.',
      category: AchievementCategory.social,
      tier: AchievementTier.bronze,
      signal: 'friend_count_peak',
      target: 1,
      iconKey: 'team_spirit',
    ),
    AchievementDefinition(
      id: 'friends_5',
      title: 'Grup Lideri',
      description: '5 Linkball arkadaşına ulaş.',
      category: AchievementCategory.social,
      tier: AchievementTier.silver,
      signal: 'friend_count_peak',
      target: 5,
      iconKey: 'group_leader',
    ),
    AchievementDefinition(
      id: 'friends_25',
      title: 'Sosyal Kaptan',
      description: '25 Linkball arkadaşına ulaş.',
      category: AchievementCategory.social,
      tier: AchievementTier.gold,
      signal: 'friend_count_peak',
      target: 25,
      iconKey: 'social_captain',
    ),
    AchievementDefinition(
      id: 'winner_5',
      title: 'Zaferin Tadı',
      description: '5 dereceli galibiyet kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.silver,
      signal: 'ranked_wins',
      target: 5,
      iconKey: 'winner_5',
    ),
    AchievementDefinition(
      id: 'winner_25',
      title: 'Tribünün Gözdesi',
      description: '25 dereceli galibiyet kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.silver,
      signal: 'ranked_wins',
      target: 25,
      iconKey: 'winner_25',
    ),
    AchievementDefinition(
      id: 'winner_250',
      title: 'Kupa Koleksiyoncusu',
      description: '250 dereceli galibiyet kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.platinum,
      signal: 'ranked_wins',
      target: 250,
      iconKey: 'winner_250',
    ),
    AchievementDefinition(
      id: 'winner_500',
      title: 'Sahanın Efsanesi',
      description: '500 dereceli galibiyet kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.platinum,
      signal: 'ranked_wins',
      target: 500,
      iconKey: 'winner_500',
    ),
    AchievementDefinition(
      id: 'winner_750',
      title: 'Linkball İkonu',
      description: '750 dereceli galibiyet kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.platinum,
      signal: 'ranked_wins',
      target: 750,
      iconKey: 'winner_750',
    ),
    AchievementDefinition(
      id: 'played_250',
      title: 'Sahanın Müdavimi',
      description: '250 dereceli maç tamamla.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.platinum,
      signal: 'ranked_played',
      target: 250,
      iconKey: 'played_250',
    ),
    AchievementDefinition(
      id: 'played_500',
      title: 'Formaya Adanmış',
      description: '500 dereceli maç tamamla.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.platinum,
      signal: 'ranked_played',
      target: 500,
      iconKey: 'played_500',
    ),
    AchievementDefinition(
      id: 'played_1000',
      title: 'Bin Maçlık Hikâye',
      description: '1000 dereceli maç tamamla.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.platinum,
      signal: 'ranked_played',
      target: 1000,
      iconKey: 'played_1000',
    ),
    AchievementDefinition(
      id: 'streak_15',
      title: 'Durdurulamaz',
      description: '15 dereceli maçı üst üste kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.platinum,
      signal: 'best_win_streak',
      target: 15,
      iconKey: 'streak_15',
    ),
    AchievementDefinition(
      id: 'streak_20',
      title: 'Kusursuz Seri',
      description: '20 dereceli maçı üst üste kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.platinum,
      signal: 'best_win_streak',
      target: 20,
      iconKey: 'streak_20',
    ),
    AchievementDefinition(
      id: 'shared_xi_wins_1',
      title: 'Ortak XI İlk Adım',
      description: 'Dereceli Ortak XI modunda 1 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.bronze,
      signal: 'ranked_shared_xi_wins',
      target: 1,
      iconKey: 'shared_xi_wins_1',
    ),
    AchievementDefinition(
      id: 'shared_xi_wins_50',
      title: 'Ortak XI Uzmanı',
      description: 'Dereceli Ortak XI modunda 50 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.gold,
      signal: 'ranked_shared_xi_wins',
      target: 50,
      iconKey: 'shared_xi_wins_50',
    ),
    AchievementDefinition(
      id: 'shared_xi_wins_100',
      title: 'Ortak XI Efsanesi',
      description: 'Dereceli Ortak XI modunda 100 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.gold,
      signal: 'ranked_shared_xi_wins',
      target: 100,
      iconKey: 'shared_xi_wins_100',
    ),
    AchievementDefinition(
      id: 'grid_wins_1',
      title: 'Grid İlk Adım',
      description: 'Dereceli Grid modunda 1 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.bronze,
      signal: 'ranked_grid_wins',
      target: 1,
      iconKey: 'grid_wins_1',
    ),
    AchievementDefinition(
      id: 'grid_wins_50',
      title: 'Grid Uzmanı',
      description: 'Dereceli Grid modunda 50 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.gold,
      signal: 'ranked_grid_wins',
      target: 50,
      iconKey: 'grid_wins_50',
    ),
    AchievementDefinition(
      id: 'grid_wins_100',
      title: 'Grid Efsanesi',
      description: 'Dereceli Grid modunda 100 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.gold,
      signal: 'ranked_grid_wins',
      target: 100,
      iconKey: 'grid_wins_100',
    ),
    AchievementDefinition(
      id: 'cinko_wins_1',
      title: 'Çinko İlk Adım',
      description: 'Dereceli Çinko modunda 1 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.bronze,
      signal: 'ranked_cinko_wins',
      target: 1,
      iconKey: 'cinko_wins_1',
    ),
    AchievementDefinition(
      id: 'cinko_wins_50',
      title: 'Çinko Uzmanı',
      description: 'Dereceli Çinko modunda 50 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.gold,
      signal: 'ranked_cinko_wins',
      target: 50,
      iconKey: 'cinko_wins_50',
    ),
    AchievementDefinition(
      id: 'cinko_wins_100',
      title: 'Çinko Efsanesi',
      description: 'Dereceli Çinko modunda 100 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.gold,
      signal: 'ranked_cinko_wins',
      target: 100,
      iconKey: 'cinko_wins_100',
    ),
    AchievementDefinition(
      id: 'five_wins_1',
      title: 'Rastgele Beş İlk Adım',
      description: 'Dereceli Rastgele Beş modunda 1 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.bronze,
      signal: 'ranked_five_wins',
      target: 1,
      iconKey: 'five_wins_1',
    ),
    AchievementDefinition(
      id: 'five_wins_50',
      title: 'Rastgele Beş Uzmanı',
      description: 'Dereceli Rastgele Beş modunda 50 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.gold,
      signal: 'ranked_five_wins',
      target: 50,
      iconKey: 'five_wins_50',
    ),
    AchievementDefinition(
      id: 'five_wins_100',
      title: 'Rastgele Beş Efsanesi',
      description: 'Dereceli Rastgele Beş modunda 100 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.gold,
      signal: 'ranked_five_wins',
      target: 100,
      iconKey: 'five_wins_100',
    ),
    AchievementDefinition(
      id: 'daily_90',
      title: 'Takvimin Efsanesi',
      description: '90 farklı günde günlük oyun sonucu kaydet.',
      category: AchievementCategory.daily,
      tier: AchievementTier.platinum,
      signal: 'daily_days',
      target: 90,
      iconKey: 'daily_90',
    ),
    AchievementDefinition(
      id: 'daily_streak_30',
      title: 'Ay Boyu Sahada',
      description: 'Günlük oyunda 30 günlük seri yap.',
      category: AchievementCategory.daily,
      tier: AchievementTier.platinum,
      signal: 'best_daily_streak',
      target: 30,
      iconKey: 'daily_streak_30',
    ),
    AchievementDefinition(
      id: 'daily_perfect_10',
      title: 'Eksiksiz Hafıza',
      description: '10 farklı günde günlük oyunu tam başarıyla bitir.',
      category: AchievementCategory.daily,
      tier: AchievementTier.gold,
      signal: 'perfect_daily_count',
      target: 10,
      iconKey: 'daily_perfect_10',
    ),
    AchievementDefinition(
      id: 'friends_10',
      title: 'Tribün Ekibi',
      description: '10 Linkball arkadaşına ulaş.',
      category: AchievementCategory.social,
      tier: AchievementTier.silver,
      signal: 'friend_count_peak',
      target: 10,
      iconKey: 'friends_10',
    ),
    AchievementDefinition(id: 'journey_chapter_1', title: 'Altın Çağın Tanığı',
      description: 'Player Journey 1. bölümündeki 8 kariyeri tamamla.', category: AchievementCategory.mastery,
      tier: AchievementTier.gold, signal: 'journey_chapter_1', target: 8, iconKey: 'journey_chapter_1'),
    AchievementDefinition(id: 'journey_chapter_2', title: 'İmkânsızı Başaranlar',
      description: 'Player Journey 2. bölümündeki 8 kariyeri tamamla.', category: AchievementCategory.mastery,
      tier: AchievementTier.gold, signal: 'journey_chapter_2', target: 8, iconKey: 'journey_chapter_2'),
    AchievementDefinition(id: 'journey_chapter_3', title: 'Oyunun Mimarları',
      description: 'Player Journey 3. bölümündeki 8 kariyeri tamamla.', category: AchievementCategory.mastery,
      tier: AchievementTier.gold, signal: 'journey_chapter_3', target: 8, iconKey: 'journey_chapter_3'),
    AchievementDefinition(id: 'journey_chapter_4', title: 'Ölümsüz İkonlar',
      description: 'Player Journey 4. bölümündeki 8 kariyeri tamamla.', category: AchievementCategory.mastery,
      tier: AchievementTier.gold, signal: 'journey_chapter_4', target: 8, iconKey: 'journey_chapter_4'),
    AchievementDefinition(id: 'journey_legend', title: 'Linkball Kariyer Efsanesi',
      description: 'Player Journey’deki 32 kariyeri tamamla.', category: AchievementCategory.mastery,
      tier: AchievementTier.platinum, signal: 'journey_total', target: 32, iconKey: 'journey_legend'),
  ];

  static final Map<String, AchievementDefinition> byId =
      <String, AchievementDefinition>{
        for (final definition in all) definition.id: definition,
      };

  static List<AchievementDefinition> forCategory(AchievementCategory category) {
    return all
        .where((definition) => definition.category == category)
        .toList(growable: false);
  }
}
