import 'achievement_models.dart';

class AchievementCatalog {
  AchievementCatalog._();

  static const int version = 1;

  static const List<AchievementDefinition> all = [
    AchievementDefinition(
      id: 'first_whistle',
      title: 'İlk Düdük',
      description: 'İlk dereceli maçını tamamla.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.bronze,
      signal: 'ranked_played',
      target: 1,
      coinReward: 10,
      iconKey: 'first_whistle',
    ),
    AchievementDefinition(
      id: 'first_victory',
      title: 'İlk Zafer',
      description: 'İlk dereceli galibiyetini al.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.bronze,
      signal: 'ranked_wins',
      target: 1,
      coinReward: 15,
      iconKey: 'first_victory',
    ),
    AchievementDefinition(
      id: 'challenger_10',
      title: 'Meydan Okuyucu',
      description: '10 dereceli maç tamamla.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.bronze,
      signal: 'ranked_played',
      target: 10,
      coinReward: 20,
      iconKey: 'challenger',
    ),
    AchievementDefinition(
      id: 'loyal_rival_50',
      title: 'Sadık Rakip',
      description: '50 dereceli maç tamamla.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.silver,
      signal: 'ranked_played',
      target: 50,
      coinReward: 40,
      iconKey: 'loyal_rival',
    ),
    AchievementDefinition(
      id: 'centurion_100',
      title: 'Yüzler Kulübü',
      description: '100 dereceli maç tamamla.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.gold,
      signal: 'ranked_played',
      target: 100,
      coinReward: 75,
      iconKey: 'centurion',
    ),
    AchievementDefinition(
      id: 'winner_10',
      title: 'Formda Günler',
      description: '10 dereceli galibiyet kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.bronze,
      signal: 'ranked_wins',
      target: 10,
      coinReward: 20,
      iconKey: 'form_days',
    ),
    AchievementDefinition(
      id: 'winner_50',
      title: 'Cesur Yürek',
      description: '50 dereceli galibiyet kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.silver,
      signal: 'ranked_wins',
      target: 50,
      coinReward: 50,
      iconKey: 'brave_heart',
    ),
    AchievementDefinition(
      id: 'winner_100',
      title: 'Zafer Makinesi',
      description: '100 dereceli galibiyet kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.gold,
      signal: 'ranked_wins',
      target: 100,
      coinReward: 100,
      iconKey: 'victory_machine',
    ),
    AchievementDefinition(
      id: 'streak_3',
      title: 'Isınan Motor',
      description: '3 dereceli maçı üst üste kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.bronze,
      signal: 'best_win_streak',
      target: 3,
      coinReward: 15,
      iconKey: 'hot_streak',
    ),
    AchievementDefinition(
      id: 'streak_5',
      title: 'Seri Katili',
      description: '5 dereceli maçı üst üste kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.silver,
      signal: 'best_win_streak',
      target: 5,
      coinReward: 40,
      iconKey: 'streak_killer',
    ),
    AchievementDefinition(
      id: 'streak_10',
      title: 'Değişmez Şampiyon',
      description: '10 dereceli maçı üst üste kazan.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.gold,
      signal: 'best_win_streak',
      target: 10,
      coinReward: 75,
      iconKey: 'unchanged_champion',
    ),
    AchievementDefinition(
      id: 'elo_1100',
      title: 'Yükselen Yıldız',
      description: 'En az 1100 Elo seviyesine ulaş.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.bronze,
      signal: 'peak_elo',
      target: 1100,
      coinReward: 20,
      iconKey: 'rising_star',
    ),
    AchievementDefinition(
      id: 'elo_1250',
      title: 'Zor Lokma',
      description: 'En az 1250 Elo seviyesine ulaş.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.silver,
      signal: 'peak_elo',
      target: 1250,
      coinReward: 50,
      iconKey: 'tough_opponent',
    ),
    AchievementDefinition(
      id: 'elo_1400',
      title: 'Sıralama Canavarı',
      description: 'En az 1400 Elo seviyesine ulaş.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.gold,
      signal: 'peak_elo',
      target: 1400,
      coinReward: 100,
      iconKey: 'ranking_beast',
    ),
    AchievementDefinition(
      id: 'elo_1600',
      title: 'Efsaneler Arasına Katıl',
      description: 'En az 1600 Elo seviyesine ulaş.',
      category: AchievementCategory.ranked,
      tier: AchievementTier.platinum,
      signal: 'peak_elo',
      target: 1600,
      coinReward: 200,
      iconKey: 'legend',
    ),
    AchievementDefinition(
      id: 'shared_xi_master',
      title: 'Ortak XI Ustası',
      description: 'Dereceli Ortak XI modunda 10 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.silver,
      signal: 'ranked_shared_xi_wins',
      target: 10,
      coinReward: 50,
      iconKey: 'shared_xi_master',
    ),
    AchievementDefinition(
      id: 'grid_master',
      title: 'Grid Ustası',
      description: 'Dereceli Grid modunda 10 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.silver,
      signal: 'ranked_grid_wins',
      target: 10,
      coinReward: 50,
      iconKey: 'grid_master',
    ),
    AchievementDefinition(
      id: 'cinko_master',
      title: 'Çinko Ustası',
      description: 'Dereceli Çinko modunda 10 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.silver,
      signal: 'ranked_cinko_wins',
      target: 10,
      coinReward: 50,
      iconKey: 'cinko_master',
    ),
    AchievementDefinition(
      id: 'five_master',
      title: 'Beşli Ustası',
      description: 'Dereceli Rastgele Beş modunda 10 galibiyet kazan.',
      category: AchievementCategory.mastery,
      tier: AchievementTier.silver,
      signal: 'ranked_five_wins',
      target: 10,
      coinReward: 50,
      iconKey: 'five_master',
    ),
    AchievementDefinition(
      id: 'daily_first',
      title: 'Takvim Çaylağı',
      description: 'İlk Günlük Mücadele sonucunu kaydet.',
      category: AchievementCategory.daily,
      tier: AchievementTier.bronze,
      signal: 'daily_days',
      target: 1,
      coinReward: 10,
      iconKey: 'calendar_rookie',
    ),
    AchievementDefinition(
      id: 'daily_7',
      title: 'Takvim Müdavimi',
      description: '7 farklı günde Günlük Mücadele oyna.',
      category: AchievementCategory.daily,
      tier: AchievementTier.bronze,
      signal: 'daily_days',
      target: 7,
      coinReward: 25,
      iconKey: 'calendar_regular',
    ),
    AchievementDefinition(
      id: 'daily_30',
      title: 'Ayın Taktisyeni',
      description: '30 farklı günde Günlük Mücadele oyna.',
      category: AchievementCategory.daily,
      tier: AchievementTier.gold,
      signal: 'daily_days',
      target: 30,
      coinReward: 75,
      iconKey: 'month_tactician',
    ),
    AchievementDefinition(
      id: 'daily_streak_7',
      title: 'Sadık Taktisyen',
      description: 'Günlük Mücadelede 7 günlük seri yap.',
      category: AchievementCategory.daily,
      tier: AchievementTier.silver,
      signal: 'best_daily_streak',
      target: 7,
      coinReward: 40,
      iconKey: 'loyal_tactician',
    ),
    AchievementDefinition(
      id: 'daily_perfect',
      title: 'Mükemmeliyetçi',
      description: 'Bir Günlük Mücadeleyi %100 başarıyla tamamla.',
      category: AchievementCategory.daily,
      tier: AchievementTier.gold,
      signal: 'perfect_daily_count',
      target: 1,
      coinReward: 60,
      iconKey: 'perfectionist',
    ),
    AchievementDefinition(
      id: 'weekly_5',
      title: 'Haftanın Savaşçısı',
      description: 'Aynı haftada 5 farklı gün skor kaydet.',
      category: AchievementCategory.daily,
      tier: AchievementTier.silver,
      signal: 'weekly_days',
      target: 5,
      coinReward: 35,
      iconKey: 'week_warrior',
    ),
    AchievementDefinition(
      id: 'first_friend',
      title: 'Takım Ruhu',
      description: 'İlk Linkball arkadaşını ekle.',
      category: AchievementCategory.social,
      tier: AchievementTier.bronze,
      signal: 'friend_count_peak',
      target: 1,
      coinReward: 10,
      iconKey: 'team_spirit',
    ),
    AchievementDefinition(
      id: 'friends_5',
      title: 'Grup Lideri',
      description: '5 Linkball arkadaşına ulaş.',
      category: AchievementCategory.social,
      tier: AchievementTier.silver,
      signal: 'friend_count_peak',
      target: 5,
      coinReward: 30,
      iconKey: 'group_leader',
    ),
    AchievementDefinition(
      id: 'friends_25',
      title: 'Sosyal Kaptan',
      description: '25 Linkball arkadaşına ulaş.',
      category: AchievementCategory.social,
      tier: AchievementTier.gold,
      signal: 'friend_count_peak',
      target: 25,
      coinReward: 100,
      iconKey: 'social_captain',
    )
  ];

  static final Map<String, AchievementDefinition> byId =
      <String, AchievementDefinition>{
    for (final definition in all) definition.id: definition,
  };

  static List<AchievementDefinition> forCategory(
    AchievementCategory category,
  ) {
    return all
        .where((definition) => definition.category == category)
        .toList(growable: false);
  }
}
