// Generated from functions/config/store_collection.json. IDs stay stable when artwork is added.
import 'user_avatar_catalog.dart';

const collectionAvatars = <UserAvatarDefinition>[
  UserAvatarDefinition(
    id: 'persona_cristiano_ronaldo',
    title: 'Cristiano Ronaldo',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_lionel_messi',
    title: 'Lionel Messi',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_neymar',
    title: 'Neymar',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_lamine_yamal',
    title: 'Lamine Yamal',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_kylian_mbappe',
    title: 'Kylian Mbappé',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_karim_benzema',
    title: 'Karim Benzema',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_luka_modric',
    title: 'Luka Modrić',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_victor_osimhen',
    title: 'Victor Osimhen',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_mauro_icardi',
    title: 'Mauro Icardi',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_erling_haaland',
    title: 'Erling Haaland',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_mohamed_salah',
    title: 'Mohamed Salah',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_anthony_nwakaeme',
    title: 'Anthony Nwakaeme',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_jose_mourinho',
    title: 'José Mourinho',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_coaches',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_pep_guardiola',
    title: 'Pep Guardiola',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_coaches',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_luis_enrique',
    title: 'Luis Enrique',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_coaches',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_fatih_terim',
    title: 'Fatih Terim',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_coaches',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_ismail_kartal',
    title: 'İsmail Kartal',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_coaches',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_okan_buruk',
    title: 'Okan Buruk',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_coaches',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_sergen_yalcin',
    title: 'Sergen Yalçın',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_coaches',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_aykut_kocaman',
    title: 'Aykut Kocaman',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_coaches',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_ronaldinho',
    title: 'Ronaldinho',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_zlatan_ibrahimovic',
    title: 'Zlatan Ibrahimović',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_ricardo_quaresma',
    title: 'Ricardo Quaresma',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_alex_de_souza',
    title: 'Alex de Souza',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_hami_mandirali',
    title: 'Hami Mandıralı',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_marek_hamsik',
    title: 'Marek Hamšík',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_zinedine_zidane',
    title: 'Zinedine Zidane',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_pele',
    title: 'Pelé',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_diego_maradona',
    title: 'Diego Maradona',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_erman_yasar',
    title: 'Erman Yaşar',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_creators',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_hasan_arda',
    title: 'Hasan Arda',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_creators',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_emre_ozcan',
    title: 'Emre Özcan',
    subtitle: 'İsimli profil avatarı',
    visualKey: 'persona_creators',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_ronaldo_nazario',
    title: 'Ronaldo Nazário',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_thierry_henry',
    title: 'Thierry Henry',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_alessandro_del_piero',
    title: 'Alessandro Del Piero',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_carles_puyol',
    title: 'Carles Puyol',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_francesco_totti',
    title: 'Francesco Totti',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_roberto_baggio',
    title: 'Roberto Baggio',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_edgar_davids',
    title: 'Edgar Davids',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_roberto_carlos',
    title: 'Roberto Carlos',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_xavi',
    title: 'Xavi',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_gennaro_gattuso',
    title: 'Gennaro Gattuso',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_david_beckham',
    title: 'David Beckham',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_steven_gerrard',
    title: 'Steven Gerrard',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_paolo_maldini',
    title: 'Paolo Maldini',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_arjen_robben',
    title: 'Arjen Robben',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_andrea_pirlo',
    title: 'Andrea Pirlo',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_gareth_bale',
    title: 'Gareth Bale',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_gianluigi_buffon',
    title: 'Gianluigi Buffon',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_sergio_ramos',
    title: 'Sergio Ramos',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_luis_suarez',
    title: 'Luis Suárez',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_petr_cech',
    title: 'Petr Čech',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_fernando_torres',
    title: 'Fernando Torres',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_andres_iniesta',
    title: 'Andrés Iniesta',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_didier_drogba',
    title: 'Didier Drogba',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_wesley_sneijder',
    title: 'Wesley Sneijder',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_mikel_arteta',
    title: 'Mikel Arteta',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_coaches',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_frank_lampard',
    title: 'Frank Lampard',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_andriy_shevchenko',
    title: 'Andriy Shevchenko',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_socrates',
    title: 'Sócrates',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_didier_deschamps',
    title: 'Didier Deschamps',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_johan_cruyff',
    title: 'Johan Cruyff',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_carlos_valderrama',
    title: 'Carlos Valderrama',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_ruud_gullit',
    title: 'Ruud Gullit',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_frank_rijkaard',
    title: 'Frank Rijkaard',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_legends',
    unlockKind: AvatarUnlockKind.shop,
  ),
  UserAvatarDefinition(
    id: 'persona_james_rodriguez',
    title: 'James Rodríguez',
    subtitle: 'Futbolcu portresi',
    visualKey: 'persona_players',
    unlockKind: AvatarUnlockKind.shop,
  ),
];

class ProfileKit {
  const ProfileKit(
    this.id,
    this.title,
    this.primary,
    this.secondary, {
    this.pattern = 'center',
  });
  final String id, title, pattern;
  final int primary, secondary;
}

const profileKits = <ProfileKit>[
  ProfileKit('kit_midnight', 'Gece Sahası', 0xFF142538, 0xFF39DAF2),
  ProfileKit('kit_sunrise', 'Gün Doğumu', 0xFFE95C39, 0xFFFFDB7D),
  ProfileKit('kit_forest', 'Orman Yeşili', 0xFF174D39, 0xFFBEF45A),
  ProfileKit('kit_violet', 'Mor Tribün', 0xFF6236A0, 0xFFE3CCFF),
  ProfileKit('kit_ice', 'Buz Mavisi', 0xFFD8F3FA, 0xFF14637A),
  ProfileKit('kit_retro', 'Retro Kaptan', 0xFF8C243C, 0xFFF0CA79),
  ProfileKit(
    'kit_galatasaray',
    'Galatasaray Esintisi',
    0xFFF6B817,
    0xFFAE1731,
    pattern: 'half',
  ),
  ProfileKit(
    'kit_fenerbahce',
    'Fenerbahçe Esintisi',
    0xFFF7D629,
    0xFF14284D,
    pattern: 'stripes',
  ),
  ProfileKit(
    'kit_besiktas',
    'Beşiktaş Esintisi',
    0xFFF4F4EE,
    0xFF202126,
    pattern: 'stripes',
  ),
  ProfileKit(
    'kit_trabzonspor',
    'Trabzonspor Esintisi',
    0xFF78243F,
    0xFF5CBADD,
    pattern: 'stripes',
  ),
  ProfileKit(
    'kit_liverpool',
    'Liverpool Esintisi',
    0xFFC82438,
    0xFFF2EADC,
    pattern: 'plain',
  ),
  ProfileKit(
    'kit_manchester_city',
    'Manchester City Esintisi',
    0xFF79BADD,
    0xFFF6F4ED,
    pattern: 'plain',
  ),
  ProfileKit(
    'kit_manchester_united',
    'Manchester United Esintisi',
    0xFFCC2531,
    0xFF272833,
    pattern: 'plain',
  ),
  ProfileKit(
    'kit_arsenal',
    'Arsenal Esintisi',
    0xFFD52B36,
    0xFFF4F3EC,
    pattern: 'sleeves',
  ),
  ProfileKit(
    'kit_real_madrid',
    'Real Madrid Esintisi',
    0xFFF5F2EA,
    0xFFCEAF55,
    pattern: 'plain',
  ),
  ProfileKit(
    'kit_barcelona',
    'Barcelona Esintisi',
    0xFF253D89,
    0xFFAE2443,
    pattern: 'stripes',
  ),
  ProfileKit(
    'kit_atletico_madrid',
    'Atlético Madrid Esintisi',
    0xFFF8F4EC,
    0xFFD0353C,
    pattern: 'stripes',
  ),
  ProfileKit(
    'kit_juventus',
    'Juventus Esintisi',
    0xFFF1F1ED,
    0xFF252730,
    pattern: 'stripes',
  ),
  ProfileKit(
    'kit_milan',
    'Milan Esintisi',
    0xFFBD2334,
    0xFF24252B,
    pattern: 'stripes',
  ),
  ProfileKit(
    'kit_inter',
    'Inter Esintisi',
    0xFF2455AB,
    0xFF20242D,
    pattern: 'stripes',
  ),
  ProfileKit(
    'kit_bayern',
    'Bayern Münih Esintisi',
    0xFFCC263D,
    0xFFE9EEF4,
    pattern: 'hoops',
  ),
  ProfileKit(
    'kit_dortmund',
    'Borussia Dortmund Esintisi',
    0xFFF5D829,
    0xFF23272F,
    pattern: 'sleeves',
  ),
  ProfileKit(
    'kit_psg',
    'Paris Saint-Germain Esintisi',
    0xFF172C55,
    0xFFC62C42,
    pattern: 'center',
  ),
  ProfileKit(
    'kit_marseille',
    'Marsilya Esintisi',
    0xFFF2F4ED,
    0xFF37A8D5,
    pattern: 'plain',
  ),
];
ProfileKit? profileKit(String id) {
  for (final kit in profileKits) {
    if (kit.id == id) return kit;
  }
  return null;
}
