#!/usr/bin/env python3
"""Generate the Flutter crop catalog from the reviewed source-card manifest."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = Path(__file__).with_name('manifest.json')
OUTPUT = ROOT / 'lib/data/season_portrait_catalog.dart'


def render(manifest):
    latest = {}
    for season, rows in manifest['seasons'].items():
        if len(rows) != 8 or any(len(row) != 7 for row in rows):
            raise ValueError(f'Expected 8 × 7 source cards: {season}')
        for r, row in enumerate(rows):
            for c, name in enumerate(row):
                latest[name] = (season, r, c)
    if set(latest) != set(manifest['playerIds']):
        raise ValueError('Every source identity must have exactly one canonical ID')
    if len(set(manifest['playerIds'].values())) != len(latest):
        raise ValueError('Multiple names share an ID')
    lines = ['// Generated by tools/season_portraits/generate_catalog.py.',
             '/// Rectangles refer to the unmodified source sheets.',
             'class SeasonPortraitSpec {',
             '  final String asset;',
             '  final double sheetWidth, sheetHeight, left, top, width, height;',
             '  const SeasonPortraitSpec({',
             *['    required this.' + field + ',' for field in
               ('asset', 'sheetWidth', 'sheetHeight', 'left', 'top', 'width', 'height')],
             '  });', '}', '', 'abstract final class SeasonPortraitCatalog {',
             '  // Canonical IDs prevent portraits leaking to namesakes.',
             '  static const Map<int, SeasonPortraitSpec> byPlayerId = {']
    for name, (season, r, c) in latest.items():
        source = manifest['sources'][season]
        grid = source['grid']
        sw, sh = source['referenceSize']
        lines.extend([
            f'    // {name}',
            f"    {manifest['playerIds'][name]}: SeasonPortraitSpec(",
            f"      asset: 'assets/season_portraits/season_{season}.jpg',",
            f'      sheetWidth: {sw},', f'      sheetHeight: {sh},',
            f"      left: {grid['x0'] + c * grid['xStep']:.1f},",
            f"      top: {grid['y0'] + r * grid['yStep']:.1f},",
            f"      width: {grid['cardWidth']},",
            f"      height: {grid['portraitHeight']},", '    ),'])
    lines += ['  };',
              '  static SeasonPortraitSpec? forPlayerId(int id) => byPlayerId[id];',
              '}', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render(json.loads(MANIFEST.read_text(encoding='utf-8')))
    if args.check:
        if OUTPUT.read_text(encoding='utf-8') != expected:
            raise SystemExit('Season crop catalog is stale; run generate_catalog.py')
        print('[PASS] Reviewed manifest and Flutter crops match.')
    else:
        OUTPUT.write_text(expected, encoding='utf-8')
