#!/usr/bin/env python3
from __future__ import annotations

import html
import json
import re
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = Path(__file__).with_name("manifest.json")
ASSET_ROOT = ROOT / "assets" / "season_portraits"
CATALOG = ROOT / "lib" / "data" / "season_portrait_catalog.dart"

UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/154.0 Safari/537.36"
)


def fetch(url: str, *, accept: str = "*/*", attempts: int = 3) -> bytes:
    last: Exception | None = None
    for attempt in range(attempts):
        try:
            req = urllib.request.Request(
                url,
                headers={"User-Agent": UA, "Accept": accept, "Referer": "https://www.behance.net/"},
            )
            with urllib.request.urlopen(req, timeout=45) as response:
                return response.read()
        except Exception as exc:  # pragma: no cover - network retry path
            last = exc
            if attempt + 1 < attempts:
                time.sleep(2 ** attempt)
    assert last is not None
    raise last


def extract_player_urls(project_url: str) -> list[str]:
    raw = fetch(project_url, accept="text/html,application/xhtml+xml").decode(
        "utf-8", errors="ignore"
    )
    raw = html.unescape(raw).replace("\\/", "/").replace("\\u002F", "/")

    patterns = [
        r'https://mir-s3-cdn-cf\.behance\.net/project_modules/disp_webp/[^"\'<>\\\s]+',
        r'https://mir-s3-cdn-cf\.behance\.net/project_modules/(?:max_1200|hd)_webp/[^"\'<>\\\s]+',
    ]
    urls: list[str] = []
    for pattern in patterns:
        for match in re.findall(pattern, raw):
            url = match.rstrip(",)]};")
            if url not in urls:
                urls.append(url)
        if len(urls) >= 56:
            break

    # Mathieu Marcou's two season projects expose the 56 player cards as the
    # first 56 disp_webp modules. Cover/footer modules use other size classes.
    disp = [u for u in urls if "/disp_webp/" in u]
    if len(disp) < 56:
        raise RuntimeError(
            f"Expected at least 56 Behance player modules from {project_url}, got {len(disp)}"
        )
    return disp[:56]


def valid_image(data: bytes) -> bool:
    return (
        data.startswith(b"RIFF")
        or data.startswith(b"\x89PNG\r\n\x1a\n")
        or data.startswith(b"\xff\xd8\xff")
    ) and len(data) > 1000


def flatten(rows: list[list[str]]) -> list[str]:
    return [name for row in rows for name in row]


def dart_key(value: str) -> str:
    return (
        value.strip()
        .lower()
        .replace("’", "'")
        .replace("–", "-")
        .replace("—", "-")
    )


def dart_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def write_catalog(manifest: dict) -> None:
    aliases: dict[str, list[str]] = manifest.get("aliases", {})
    mapping: dict[str, str] = {}

    # Prefer the newer 2013/14 portrait where the same player appears twice.
    for season in ("2012_13", "2013_14"):
        names = flatten(manifest["seasons"][season])
        for index, name in enumerate(names, start=1):
            path = f"assets/season_portraits/{season}/{index:02d}.img"
            keys = [name, *aliases.get(name, [])]
            for key in keys:
                mapping[dart_key(key)] = path

    lines = [
        "// GENERATED by tools/season_portraits/publish.py. Do not edit by hand.",
        "abstract final class SeasonPortraitCatalog {",
        "  static const Map<String, String> _byName = {",
    ]
    for key in sorted(mapping):
        lines.append(f"    '{dart_quote(key)}': '{mapping[key]}',")
    lines += [
        "  };",
        "",
        "  static String? forPlayerName(String name) {",
        '    final key = name.trim().toLowerCase().replaceAll(\'’\', "\'");',
        "    return _byName[key];",
        "  }",
        "}",
        "",
    ]
    CATALOG.parent.mkdir(parents=True, exist_ok=True)
    CATALOG.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    ASSET_ROOT.mkdir(parents=True, exist_ok=True)
    index: dict[str, list[dict[str, str]]] = {}

    for season in ("2012_13", "2013_14"):
        names = flatten(manifest["seasons"][season])
        if len(names) != 56:
            raise RuntimeError(f"{season} must contain exactly 56 names, got {len(names)}")

        source = manifest["sources"][season]["url"]
        urls = extract_player_urls(source)
        target_dir = ASSET_ROOT / season
        target_dir.mkdir(parents=True, exist_ok=True)
        records: list[dict[str, str]] = []

        for i, (name, url) in enumerate(zip(names, urls), start=1):
            data = fetch(url, accept="image/avif,image/webp,image/png,image/jpeg,*/*")
            if not valid_image(data):
                raise RuntimeError(f"Downloaded invalid image for {season} #{i}: {url}")
            path = target_dir / f"{i:02d}.img"
            path.write_bytes(data)
            records.append({"name": name, "asset": str(path.relative_to(ROOT)), "source": url})

        index[season] = records
        print(f"{season}: published {len(records)} portraits")

    (ASSET_ROOT / "index.json").write_text(
        json.dumps(index, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    write_catalog(manifest)
    print("Season portrait catalog generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
