// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKiyJZjIsk8bttfHWD4kN3xvfJcD-4ktE',
    appId: '1:702685230752:web:cddbca55c5fd1b8c77fbc5',
    messagingSenderId: '702685230752',
    projectId: 'sharedix',
    authDomain: 'sharedix.firebaseapp.com',
    storageBucket: 'sharedix.firebasestorage.app',
    measurementId: 'G-KQ2Y7PECFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj5Z5tPCsX8oQV1Lp_9Umvyn9lKZrX-vY',
    appId: '1:702685230752:android:64fa1e34523b7b5677fbc5',
    messagingSenderId: '702685230752',
    projectId: 'sharedix',
    storageBucket: 'sharedix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAZJzCvwRtkx-m3zW0iKKL4HhTi-JgEiM',
    appId: '1:702685230752:ios:1dc28b720d7e3b9677fbc5',
    messagingSenderId: '702685230752',
    projectId: 'sharedix',
    storageBucket: 'sharedix.firebasestorage.app',
    iosBundleId: 'com.example.sharedXi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAZJzCvwRtkx-m3zW0iKKL4HhTi-JgEiM',
    appId: '1:702685230752:ios:1dc28b720d7e3b9677fbc5',
    messagingSenderId: '702685230752',
    projectId: 'sharedix',
    storageBucket: 'sharedix.firebasestorage.app',
    iosBundleId: 'com.example.sharedXi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKiyJZjIsk8bttfHWD4kN3xvfJcD-4ktE',
    appId: '1:702685230752:web:a8214d021e4577df77fbc5',
    messagingSenderId: '702685230752',
    projectId: 'sharedix',
    authDomain: 'sharedix.firebaseapp.com',
    storageBucket: 'sharedix.firebasestorage.app',
    measurementId: 'G-TXXL67RBM7',
  );
}
