// Generated by STEP 08B.2.
// Public compliance contact/config. Do not put secrets in this file.

class PrivacyConfig {
  PrivacyConfig._();

  static const String contactEmail = 'burakozturk1315@gmail.com';
  static const String privacyPolicyUrl =
      'https://sharedix.web.app/privacy.html';
  static const String accountDeletionUrl =
      'https://sharedix.web.app/account-deletion.html';
}
