#!/usr/bin/env python3
"""Generate portrait mappings and the client avatar collection from reviewed data."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def quoted(value):
    return "'" + str(value).replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') + "'"


def render(manifest):
    lines = ['// Generated by tools/uploaded_portraits/generate_catalog.py.',
             "import 'season_portrait_catalog.dart';", '',
             'abstract final class UploadedPortraitCatalog {',
             '  static const Map<String, SeasonPortraitSpec> portraits = {']
    players = {}
    player_roles = {}
    for p in manifest['portraits']:
        source = manifest['sources'][p['source']]
        w, h = source['size']
        x, y, cw, ch = p['crop']
        assert 0 <= x < x + cw <= w and 0 <= y < y + ch <= h
        lines += [f"    {quoted(p['key'])}: SeasonPortraitSpec(",
                  f"      asset: {quoted(source['asset'])},",
                  f'      sheetWidth: {w}, sheetHeight: {h},',
                  f'      left: {x}, top: {y}, width: {cw}, height: {ch},', '    ),']
        if p['playerId'] is not None:
            # Explicit role wins independently of manifest/source ordering.
            if p['role'] == 'player' or player_roles.get(p['playerId']) != 'player':
                players[p['playerId']] = p['key']
                player_roles[p['playerId']] = p['role']
    lines += ['  };']
    for field, mapping, key_type, val_type in [
        ('playerKeys', players, 'int', 'String'),
        ('avatarKeys', manifest['avatarKeys'], 'String', 'String'),
        ('avatarPlayerIds', manifest['avatarPlayerIds'], 'String', 'int'),
        ('coachKeys', manifest['coachKeys'], 'String', 'String'),
        ('coachPlayerIds', manifest['coachPlayerIds'], 'String', 'int'),
    ]:
        lines += [f'  static const Map<{key_type}, {val_type}> {field} = {{']
        for key, value in mapping.items():
            lines += [f'    {key if key_type == "int" else quoted(key)}: {value if val_type == "int" else quoted(value)},']
        lines += ['  };']
    lines += [
        '  static SeasonPortraitSpec? forPlayerId(int id) => portraits[playerKeys[id]];',
        '  static SeasonPortraitSpec? forAvatarId(String id) => portraits[avatarKeys[id]];',
        '  static SeasonPortraitSpec? forCoachId(String id) => portraits[coachKeys[id]];',
        '}', '']
    return '\n'.join(lines)


def render_avatars(catalog, current):
    prefix = ["// Generated from functions/config/store_collection.json. IDs stay stable when artwork is added.",
              "import 'user_avatar_catalog.dart';", '',
              'const collectionAvatars = <UserAvatarDefinition>[']
    for offer in catalog['offers']:
        if offer['itemType'] != 'avatar' or not offer['enabled']:
            continue
        prefix += ['  UserAvatarDefinition(',
                   f"    id: {quoted(offer['itemId'])},",
                   f"    title: {quoted(offer['title'])},",
                   f"    subtitle: {quoted(offer['subtitle'].split(' · ')[0])},",
                   f"    visualKey: {quoted('persona_' + offer['category'])},",
                   '    unlockKind: AvatarUnlockKind.shop,', '  ),']
    prefix += ['];', '']
    return '\n'.join(prefix) + '\nclass ProfileKit {' + current.split('\nclass ProfileKit {', 1)[1]


def render_coaches():
    review = json.loads((ROOT / 'tools/data_platform_v4/patches/avatar-careers-2026-10-05.json').read_text())
    lines = ['// Generated by tools/uploaded_portraits/generate_catalog.py.',
             "import '../models/coach.dart';", '',
             'abstract final class ReviewedPortraitCoaches {',
             '  static const List<Coach> coaches = [']
    for c in review['coaches']:
        strings = lambda xs: '[' + ', '.join(quoted(x) for x in xs) + ']'
        lines += ['    Coach(', f"      id: {quoted(c['id'])}, name: {quoted(c['name'])},",
                  f"      countries: {strings(c['countries'])}, clubIds: {c['clubIds']},",
                  f"      aliases: {strings(c['aliases'])}, avatarKey: {quoted(c['avatarKey'])},",
                  f"      rating: {c['rating']},", '    ),']
    lines += ['  ];', '  static const Set<String> replacedIds = {']
    for cid in sorted({cid for c in review['coaches'] for cid in c['legacyIds'] + [c['id']]}):
        lines += [f'    {quoted(cid)},']
    lines += ['  };', '}', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    manifest = json.loads(Path(__file__).with_name('manifest.json').read_text())
    catalog = json.loads((ROOT / 'functions/config/store_collection.json').read_text())
    avatar_path = ROOT / 'lib/models/store_collection.dart'
    outputs = {
        ROOT / 'lib/data/uploaded_portrait_catalog.dart': render(manifest),
        avatar_path: render_avatars(catalog, avatar_path.read_text()),
        ROOT / 'lib/data/reviewed_portrait_coaches.dart': render_coaches(),
    }
    for path, content in outputs.items():
        if args.check:
            if path.read_text() != content:
                raise SystemExit(f'Stale generated file: {path}')
        else:
            path.write_text(content)
    print('[PASS] Uploaded portrait and avatar catalogs agree.')


if __name__ == '__main__':
    main()
