from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[2]
REPORTS = ROOT / "reports" / "production"

removed = []
skipped = []

if REPORTS.exists():
    for snapshot in REPORTS.rglob("snapshot"):
        if not snapshot.is_dir():
            continue

        manifest = snapshot / "SNAPSHOT_MANIFEST.txt"

        # Only remove folders generated by our source-snapshot tools.
        if not manifest.exists():
            skipped.append(snapshot)
            continue

        parent = snapshot.parent
        zip_outputs = list(parent.glob("*.zip"))

        # Preserve the packaged snapshot ZIP. The raw extracted snapshot
        # directory is only a temporary duplicate of project source.
        if not zip_outputs:
            skipped.append(snapshot)
            continue

        shutil.rmtree(snapshot)
        removed.append(snapshot)

print("==========================================================")
print("STEP 07A.8.1 - GENERATED SNAPSHOT CLEANUP")
print("==========================================================")
print()

if removed:
    for path in removed:
        print("[CLEAN]", path.relative_to(ROOT))
else:
    print("[INFO] No generated snapshot directories needed cleanup.")

if skipped:
    print()
    print("[SAFE] Unrecognized snapshot folders were left untouched:")
    for path in skipped:
        print("  -", path.relative_to(ROOT))

print()
print("[SAFE] Snapshot ZIP files were preserved.")
print("[SAFE] lib/, android/, Firebase and signing files were not touched.")
